<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => '',
    'Add Chapter Page' => '',
    'Add an existent page' => '',
    'Are you sure you want to delete this item?' => '',
    'As you see, Marta\'s story continues. She, like you, is committed to transforming her community. That\'s why you have {points} points in the power of Transformation.<br><br>You have always had this power. Now it is time to discover your other hidden powers.' => '',
    'Chapter' => '',
    'Chapter #{number}' => '',
    'Chapter Number' => '',
    'Chapter Pages' => '',
    'Chapters' => '',
    'Create' => '',
    'Create Chapter' => '',
    'Create New Novel' => '',
    'Create new page' => '',
    'Delete' => '',
    'Discover Your Powers' => '',
    'Edit' => '',
    'Edit ' => '',
    'Graphic Novel' => '',
    'Graphic Novels' => '',
    'ID' => '',
    'Image' => '',
    'Language' => '',
    'Leave it empty to use a image instead' => '',
    'Markup' => '',
    'Mission' => '',
    'No chapter page added yet!' => '',
    'No images uploaded yet' => '',
    'Novel' => '',
    'Novel #{number}' => '',
    'Page ID' => '',
    'Page Image' => '',
    'Page Number' => '',
    'Remove from Chapter' => '',
    'Select Language' => '',
    'Select Mission' => '',
    'Select Page' => '',
    'This mission is already associated to a chapter, choose another one.' => '',
    'Update' => '',
    'Uploaded Image: {file}' => '',
    'View pages' => '',
];
