<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Select Language' => 'Select Language',
    'Select Mission' => 'Select Mission',
    'Activities' => 'Activities',
    'Activity' => 'Activity',
    'Add Translations' => 'Add Translations',
    'Are you sure you want to delete this activity?' => 'Are you sure you want to delete this activity?',
    'Are you sure you want to delete this mission?' => 'Are you sure you want to delete this mission?',
    'Are you sure you want to delete this translation?' => 'Are you sure you want to delete this translation?',
    'Create' => 'Create',
    'Create new Activity' => 'Create new Activity',
    'Create new Mission' => 'Create new Mission',
    'Create new Translation' => 'Create new Translation',
    'Delete' => 'Delete',
    'Description' => 'Description',
    'Edit' => 'Edit',
    'ID' => 'ID',
    'ID Code' => 'ID Code',
    'Language' => 'Language',
    'Mission' => 'Mission',
    'Missions' => 'Missions',
    'No activities created yet!' => 'No activities created yet!',
    'No activity translations created yet!' => 'No activity translations created yet!',
    'No mission translations created yet!' => 'No mission translations created yet!',
    'No missions created yet!' => 'No missions created yet!',
    'Reset' => 'Reset',
    'Search' => 'Search',
    'Title' => 'Title',
    'Translation' => 'Translation',
    'Translations' => 'Translations',
    'Update' => 'Update',
    'Update Activity' => 'Update Activity',
    'Update Mission' => 'Update Mission',
    'Update Translation' => 'Update Translation',
    'View Activities' => 'View Activities',
    'View translations' => 'View translations',
];
