<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<Strong> This video will be the basis that other agents and mentors will take to know whether or not to invest in your Evokation. </ Strong>' => '',
    'Agent, here you can check together with your team the draft of your Evokation. Remember that team captains should send the video summary about your proposed solution, or better known as Elevator Pitch.' => '',
    'Error' => '',
    'Evokation updated!' => '',
    'Evokations' => '',
    'Google Drive URL' => '',
    'Google Drive URL:' => '',
    'If you achieve enough investment (to be within the top 10), an expert committee will evaluate the final Evokation document to decide the winners.' => '',
    'No categories created yet!' => '',
    'Remember to review the feedback you received from mentors and other agents, as well as weekly reflections, to update the final Evokation document before handing it over to your mentor teachers and finalizing it on the platform.' => '',
    'See Elevator Pitch' => '',
    'See results' => '',
    'Something went wrong' => '',
    'Submit Elevator Pitch' => '',
    'Team Progress: {number}%' => '',
    'Update' => '',
    'Updated' => '',
    'Vote on Evokations' => '',
    'Voting Closed' => '',
    'You can access it through the following link:' => '',
    '{name}\'s Evokation' => '',
];
