<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
<<<<<<< HEAD
    'GENERAL RANKINGS' => '',
=======
    'Leaderboard' => '',
    'My Evidences Submitted: {evidences}' => '',
>>>>>>> f5466e1a9a7dcb492a6d8e680f8e5fab835fe9ed
    'My Position: Not Ranked' => '',
    'My Position: {position}' => '',
    'My Reviews Submitted: {evidences}' => '',
    'My Score: {average}' => '',
    'My Team\'s Evidences Submitted: {evidences}' => '',
    'My Team\'s Evidences Submitted: {reviews}' => '',
    'My Team\'s Improvement: {rating}' => '',
    'My Team\'s Position: #{position}' => '',
    'My Team\'s Position: Not Ranked' => '',
    'My Team\'s Position: {position}' => '',
<<<<<<< HEAD
    'POWERS RANKING' => '',
    'SELECT POWER' => '',
    'TEAMS RANKING' => '',
    'Top Agents By {title}' => '',
=======
    'My Team\'s Reviews Submitted: {evidences}' => '',
    'Top Agents By Average Score' => '',
    'Top Agents By Evidences Submitted' => '',
    'Top Agents By Reviews Given' => '',
>>>>>>> f5466e1a9a7dcb492a6d8e680f8e5fab835fe9ed
    'Top Mentors By Reviews Given' => '',
    'Top Teams By Mentor Review Improvement' => '',
    'Top Teams By Quality Evidences Given' => '',
    'Top Teams By Quality Reviews Given' => '',
    'You are a mentor' => '',
];
