<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calvin Klein – Between love and madness lies obsession.' => 'Calvin Klein - Entre el amor y la locura está la obsesión.',
    'Nike – Just buy it. ;Wink;' => 'Nike - sólo cómpralo. ;Wink;',
    'We\'re looking for great slogans of famous brands. Maybe you can come up with some samples?' => 'Estamos en busca de grandes lemas de marcas famosas. Tal vez se puede llegar a algunas muestras ?',
    'Welcome Space' => 'Espacio de bienvenida',
    'Yay! I\'ve just installed HumHub ;Cool;' => '¡Hurra! Acabo de instalar HumHub ;Cool;',
    'Your first sample space to discover the platform.' => 'Su primer espacio de muestra para descubrir la plataforma',
    'Create Admin Account' => 'Crear cuenta de administrador',
];
