<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow access for non-registered users to public content (guest access)' => 'Permitir el acceso de usuarios no registrados al contenido público (acceso para invitados)',
    'External user can register (The registration form will be displayed at Login)' => 'Usuario externo puede registrar (El formulario de inscripción se mostrará al iniciar sesión)',
    'Newly registered users have to be activated by an admin first' => 'Nuevos usuarios registrados tienen que ser activada por un administrador primera',
    'Registered members can invite new users via email' => 'Los miembros registrados pueden invitar a nuevos usuarios vía e-mail',
];
