<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'HumHub is very flexible and can be adjusted and/or expanded for various different applications thanks to its’ different modules.  The following modules are just a few examples and the ones we thought are most important for your chosen application.<br><br>You can always install or remove modules later. You can find more available modules after installation in the admin area.' => 'HumHub es muy flexible y se puede ajustar y/o se expande para varios diferentes aplicaciones gracias a sus diferentes módulos. Los siguientes módulos son sólo unos pocos ejemplos y los que pensamos que es más importante para la aplicación seleccionada.<br><br> Usted siempre puede instalar o retirar módulos más tarde. Puede encontrar más módulos disponibles después de la instalación en el área de administración.',
    'Recommended <strong>Modules</strong>' => '<strong>Módulos</strong> Recomendados',
];
