<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Configuration</strong>' => '<strong>Configuración</strong>',
    'My club' => 'Mi club',
    'My community' => 'Mi comunidad',
    'My company (Social Intranet / Project management)' => 'Mi empresa (Intranet Social / Gestión de proyectos)',
    'My educational institution (school, university)' => 'Mi institución educativa (escuela, universidad)',
    'Skip this step, I want to set up everything manually' => 'Omitir este paso, quiero configurar todo manualmente',
    'To simplify the configuration, we have predefined setups for the most common use cases with different options for modules and settings. You can adjust them during the next step.' => 'Para simplificar la configuración , tenemos configuraciones predefinidas para los casos de uso más comunes con diferentes opciones para los módulos y la configuración. Puede ajustarlos durante el paso siguiente ',
];
