<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'Identificación',
    'Select Language' => 'Seleccione el idioma',
    'Select Mission' => 'Seleccione la misión',
    'Activities' => 'Actividades',
    'Activity' => 'Actividad',
    'Add Translations' => 'Añadir Traducción',
    'Are you sure you want to delete this activity?' => 'Estás seguro que quieres eliminar esta actividad?',
    'Are you sure you want to delete this mission?' => 'Estás seguro que quieres eliminar esta misión?',
    'Are you sure you want to delete this translation?' => 'Estás seguro que quieres eliminar esta traducción?',
    'Create' => 'Crear',
    'Create new Activity' => 'Crear nueva Actividad',
    'Create new Mission' => 'Crear nueva Misión',
    'Create new Translation' => 'Crear nueva traducción',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Edit' => 'Editar',
    'ID Code' => 'Código de identificación',
    'Language' => 'Idioma',
    'Mission' => 'Misión',
    'Missions' => 'Misiones',
    'No activities created yet!' => 'No hay actividades creadas aún!',
    'No activity translations created yet!' => 'No hay traducciones de actividad creadas aún!',
    'No mission translations created yet!' => 'No hay traducciones de misión creadas aún!',
    'No missions created yet!' => 'No hay misiones creadas aún!',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Title' => 'Título',
    'Translation' => 'Traducción',
    'Translations' => 'Traducciones',
    'Update' => 'Actualizar',
    'Update Activity' => 'Actualizar Actividad',
    'Update Mission' => 'Actualizar Misión',
    'Update Translation' => 'Actualizar Traducción',
    'View Activities' => 'Ver Actividades',
    'View translations' => 'Ver Traducciones',
];
