<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You just gained 10 points in {message}' => 'Has ganado 10 puntos en {mensaje}',
    'Activities' => 'Actividades',
    'Activity' => 'Actividad',
    'Activity Powers' => 'Poderes de Actividades',
    'Activity {activity}' => 'Actividad {activity}',
    'Activity:' => 'Actividades',
    'Add new Power' => 'Añadir nuevo Power',
    'Are you sure you want to delete this activity?' => 'Estás seguro que quieres eliminar esta actividad?',
    'Are you sure you want to delete this mission?' => 'Estás seguro que quieres eliminar esta misión?',
    'Are you sure you want to delete this power?' => 'Estás seguro que quieres eliminar este poder?',
    'Are you sure you want to delete this translation?' => 'Estás seguro que quieres eliminar esta traducción?',
    'Choose Mission' => 'Elija una Misión',
    'Choose an Activity:' => 'Elija una Actividad',
    'Choose how many points you will award this evidence.' => 'Elegir la cantidad de puntos que otorgará esta evidencia.',
    'Close' => 'Cerrar',
    'Congratulations!' => '¡Felicitaciones!',
    'Create' => 'Crear',
    'Create an Evidence for this Activity:' => 'Crear una Evidencia para esta Actividad',
    'Create new Activity' => 'Crear nueva Actividad',
    'Create new Mission' => 'Crear nueva Misión',
    'Create new Translation' => 'Crear nueva traducción',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Distribute points for {title}' => 'Distribuir los puntos de {title}',
    'Edit' => 'Editar',
    'Enter Activity' => 'Entrar en la actividad',
    'Enter Mission' => 'Entrar en la misión',
    'For every piece of evidence you review, you receive 10 points in {title}' => 'Por cada pieza de evidencia que revise, recibe 10 puntos en {title}',
    'How many points will you award this evidence?' => '¿Cuántos puntos se le concederá esta evidencia?',
    'ID Code' => 'Código ID',
    'Language' => 'Idioma',
    'Mission' => 'Misión',
    'Mission {mission}: Activities' => 'Misión {mission}: Actividades',
    'Mission:' => 'Misión',
    'Mission: {alias}' => 'Misión: {alias}',
    'Missions' => 'Misiones',
    'Missions Module Configuration' => 'Configuración del Módulo de Misiones',
    'No activities created yet!' => 'No hay actividades creadas aún!',
    'No activity powers created yet!' => 'No hay poderes de actividad creadas aún!',
    'No activity translations created yet!' => 'No hay traducciones de actividad creadas aún!',
    'No mission translations created yet!' => 'No hay traducciones de misión creadas aún!',
    'No missions created yet!' => 'No hay misiones creadas aún!',
    'Nothing here.' => 'Nada aquí',
    'Please, Answer yes or no.' => 'Por favor, contesta sí o no.',
    'Points' => 'Pontos',
    'Primary Power' => 'Poder Primario',
    'Reset' => 'Reiniciar',
    'Review' => 'Opinión',
    'Search' => 'Buscar',
    'Secondary Power' => 'Poder Secundario',
    'Select Difficulty Level' => 'Seleccione el nivel de dificultad',
    'Select Language' => 'Seleccionar idioma',
    'Select Mission' => 'Seleccionar Misión',
    'Select Option' => 'Seleccionar opción',
    'Select Power' => 'Seleccionar poder',
    'Submit Review' => 'Enviar opinión',
    'Title' => 'Título',
    'Translation' => 'Traducción',
    'Translations' => 'Traducciones',
    'Type (Primary/Secondary)' => 'Tipo (Primario/Secundario)',
    'Unavailable - Rate Evidence' => 'No disponible – Evaluar Evidencia',
    'Unavailable - Read Missions' => 'No disponible – Lea las Misiones',
    'Update' => 'Actualizar',
    'Update Activity' => 'Actualizar Actividad',
    'Update Mission' => 'Actualizar Misión',
    'Update Translation' => 'Actualizar Traducción',
    'View' => 'Ver',
    'View Activities' => 'Ver Actividades',
    'View Powers' => 'Ver Poderes',
    'View Translations' => 'Ver Traducciones',
    'View translations' => 'Ver traducciones',
    'You just gained' => 'Has ganado',
    'Your review was updated!' => 'Su revisión fue actualizado!',
    'and' => 'y',
    '{message}. <BR>Thank you for your review.' => '{message}. <BR>Gracias por su opinión.',
];
