<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
<<<<<<< HEAD
    'Tag Evidences' => 'Etiquetas de Evidencías',
    'Tags' => 'Etiquetas',
=======
    'Review Evidences' => 'Revisar Evidencías',
    'Tag Evidences' => 'Etiquetar Evidencías',
>>>>>>> f5466e1a9a7dcb492a6d8e680f8e5fab835fe9ed
    'All Evidences' => 'Todas las Evidencias',
    'Evidences' => 'Evidencias',
    'Evokation' => 'Evokación',
    'Evokation Categories' => 'Categorías de Evokación',
    'Evokation Deadline' => 'Fin de plazo de Evokación',
    'Evokations' => 'Evokations',
    'Evoke Errors\' View' => 'Visualización de Errors de Evoke',
    'Evoke Settings' => 'Ajustes de Evoke',
    'Members' => 'Miembros',
    'Missions' => 'Misiones',
    'My Team' => 'Mi Equipo',
    'My Teams' => 'Mis equipos',
    'Reviews' => 'Evaluaciones',
    'Tags' => 'Etíquetas',
];
