<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Agent, here you can check together with your team the draft of your Evokation. Remember that team captains should send the video summary about your proposed solution, or better known as Elevator Pitch.' => 'Agente, aquí puedes revisar en conjunto con tu equipo el borrador de tu Evokación. Recuerda que los capitanes de equipo deberán enviar el video resumen sobre tu propuesta de solución, o mejor conocido como Elevator Pitch (discurso del ascensor).',
    'If you achieve enough investment (to be within the top 10), an expert committee will evaluate the final Evokation document to decide the winners.' => 'Si logras suficiente inversión (estar dentro de las 10 más votadas), un comité experto evaluará el documento de tu Evokación final para decidir cuáles son las ganadoras.',
    'Remember to review the feedback you received from mentors and other agents, as well as weekly reflections, to update the final Evokation document before handing it over to your mentor teachers and finalizing it on the platform.' => 'Recuerda revisar la retroalimentación que recibiste de los mentores y de otros agentes, así como las reflexiones semanales, para actualizar el documento de la Evokación final antes de entregarlo a tus profesores mentores y finalizarlo en la plataforma.',
    'You can access it through the following link:' => 'Puedes accederlo a través del siguiente enlace:',
    '<Strong> This video will be the basis that other agents and mentors will take to know whether or not to invest in your Evokation. </ Strong>' => '<strong>Ese video será la base que tomarán otros agentes y mentores para saber si invierten o no en tu Evokación.</strong>',
    'Error' => 'Error',
    'Evokation Deadline: {deadline} ({timezone})' => 'Prazo final de Evokation: {deadline} ({timezone})',
    'Evokation updated!' => 'Evokación actualizada!',
    'Evokations' => 'Evokaciones',
    'Google Drive URL' => 'Google Drive URL',
    'Google Drive URL:' => 'Google Drive URL:',
    'No categories created yet!' => 'No hay categorías creadas aún!',
    'See Elevator Pitch' => 'Ver el Discurso del Ascensor',
    'See results' => 'Ver resultados',
    'Something went wrong' => 'Algo salió mal',
    'Submit Elevator Pitch' => 'Enviar el Discurso del Ascensor (Elevator Pitch)',
    'Team Progress: {number}%' => 'Progreso del equipo: {number}%',
    'Update' => 'Actualizar',
    'Updated' => 'Actualizado',
    'Vote on Evokations' => 'Voto en Evokaciones',
    'Voting Closed' => 'La votación está cerrada',
    '{name}\'s Evokation' => 'Evokación de {name}',
];
