<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'GENERAL RANKINGS' => 'RANKINGS GENERALES',
    'My Team\'s Evidences Submitted: {reviews}' => 'Evidencias Publicadas de mi equipo: {reviews}',
    'My Team\'s Improvement: {rating}' => 'Mejora de mi equipo: {rating}',
    'My Team\'s Position: #{position}' => 'Posición de mi equipo: #{position}',
    'POWERS RANKING' => 'RANKING DE PODERES',
    'SELECT POWER' => 'SELECCIONAR PODER',
    'TEAMS RANKING' => 'RANKING DE EQUIPOS',
    'Top Agents By {title}' => 'Mejores agentes por {title}',
    'Top Teams By Mentor Review Improvement' => 'Mejores equipos por mejora de evaluaciones de mentores',
    'Top Teams By Quality Evidences Given' => 'Mejores equipos por evidencias de calidad',
    'Top Teams By Quality Reviews Given' => 'Mejores equipos por calidad de evaluación',
    'You are a mentor' => 'Eres un mentor',
    'My Score: {average}' => 'Mi puntuación: {average}',
    'Top Agents By Average Score' => 'Mejores equipos considerando puntuación média',
    'Leaderboard' => 'Clasificación',
    'My Evidences Submitted: {evidences}' => 'Mis Evidencias Publicadas: {evidences}',
    'My Position: Not Ranked' => 'Mi Posición: Sin puntaje',
    'My Position: {position}' => 'Mi Posición: {position}',
    'My Reviews Submitted: {evidences}' => 'Mis Revisiones Realizadas: {evidences}',
    'My Reviews Submitted:: {evidences}' => 'Mis Revisiones Realizadas {evidences}',
    'My Team\'s Evidences Submitted: {evidences}' => 'Evidencias Publicadas de mi equipo: {evidences}',
    'My Team\'s Position: Not Ranked' => 'Posición de mi equipo: Sin puntaje',
    'My Team\'s Position: {position}' => 'Posición de mi equipo: {position}',
    'Top Mentors By Reviews Given' => 'Mejores mentores considerando Revisiones Realizadas',
];
