<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Leaderboard' => 'La tabla de posiciones',
    'My Evidences Submitted: {evidences}' => 'Mis Evidencias Publicadas: {evidences}',
    'My Position: Not Ranked' => 'Mi Posición: Sin puntaje',
    'My Position: {position}' => 'Mi Posición: {position}',
    'My Reviews Submitted: {evidences}' => 'Mis Revisiones Publicadas: {evidences}',
    'My Team\'s Evidences Submitted: {evidences}' => 'Evidencias Publicadas de mi equipo: {evidences}',
    'My Team\'s Position: Not Ranked' => 'Posición de mi equipo: Sin puntaje',
    'My Team\'s Position: {position}' => 'Posición de mi equipo: {position}',
    'My Team\'s Reviews Submitted: {evidences}' => 'Revisiones Publicadas de mi equipo: {evidences}',
    'Top Agents By Evidences Submitted' => 'Mejores agentes considerando Evidencias Publicadas',
    'Top Agents By Reviews Given' => 'Mejores agentes por Revisiones Publicadas',
    'Top Mentors By Reviews Given' => 'Mejores mentores por Revisiones Publicadas',
    'Top Teams By Evidences Submitted' => 'Mejores equipos considerando Evidencias Publicadas',
    'Top Teams By Reviews Given' => 'Mejores equipos considerando Revisiones Publicadas',
];
