<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Novel Chapter #{number}' => '',
    'Activities' => 'Actividades',
    'Activities ID' => 'Identificación de Actividades',
    'Activity ID' => 'Identificación de Actividad',
    'Activity Powers' => 'Poderes de actividad',
    'Activity Translations' => 'Traducciones de actividad',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea eliminar este artículo?',
    'Chapter #{chapter} - Page #{page}' => 'Capítulo #{chapter} - Página #{page}',
    'Comment' => 'Comentario',
    'Create' => 'Crear',
    'Create Activities' => 'Create Actividades',
    'Create Activity Powers' => 'Create Poderes de Actividades',
    'Create Activity Translations' => 'Crear traducciones de actividad',
    'Create Mission Translations' => 'Crear traducciones de misión',
    'Created At' => 'Creado en',
    'Created By' => 'Creado por',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Develop' => 'Desarrollar',
    'Difficulty Level ID' => 'Identificación de nivel de dificultad',
    'Evidence Success Message' => 'Mensaje de éxito de evidencía',
    'Evokation Category ID' => 'Identificación de Categoria de Evocation',
    'Flag' => 'Flag',
    'Group Activity' => 'Actividad Grupal',
    'ID' => 'Identificación',
    'Id Code' => 'Código de identificación',
    'Is a Group Activity' => 'Es una Actividad Grupal',
    'Language ID' => 'Identificación de idioma',
    'Locked' => 'Bloqueado',
    'Mission ID' => 'Identificación de misión',
    'Mission Translations' => 'Traducciones de misión',
    'Modified At' => 'Modificado en',
    'No, it does not meet the activity\'s requirement' => 'No, no cumple con el requisito de la actividad',
    'Points' => 'Puntos',
    'Position' => 'Posición',
    'Power ID' => 'Identificación de poder',
    'Reset' => 'Reiniciar',
    'Rubric' => 'Rubrica',
    'Search' => 'Buscar',
    'Skill ID' => 'Identificación de habilidad',
    'Text' => 'Texto',
    'Title' => 'Título',
    'Update' => 'Actualizar',
    'Updated At' => 'Actualizado en',
    'Updated By' => 'Actualizado por',
    'Value' => 'Valor',
    'Youtube Url' => 'Url de Youtube',
];
