git rm -r --cached protected/config/*
git rm -r --cached protected/runtime/*
git rm -r --cached protected/data/*.db
git rm -r --cached assets/*
git rm -r --cached uploads/*
git rm -r --cached protected/modules/books
git rm -r --cached protected/modules/custom_pages
git rm -r --cached protected/modules/mail
git rm -r --cached protected/modules/polls
git rm -r --cached protected/modules/birthday
git rm -r --cached protected/modules/breakingnews
git rm -r --cached protected/modules/wiki
git rm -r --cached protected/modules/books/*
git rm -r --cached protected/modules/custom_pages/*
git rm -r --cached protected/modules/mail/*
git rm -r --cached protected/modules/polls/*
git rm -r --cached protected/modules/birthday/*
git rm -r --cached protected/modules/birthday/*
git rm -r --cached protected/modules/breakingnews/*
git rm -r --cached protected/modules/wiki/*
