<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This user must answer psychometric questionnaire first.' => 'Este usuario debe responder el cuestionario psicométrico primero.',
    'points' => 'pontos',
    'Are you sure you want to delete this item?' => 'Estás seguro que quieres eliminar este ítem?',
    'Create Power Translation' => 'Crear traducción de poder',
    'Create Powers' => 'Crear Poderes',
    'Create new Power' => 'Crear nuevo Poder',
    'Create new Power Translation' => 'Crear nueva traducción de poder',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'No matching questions created yet!' => 'No existen preguntas asociadas aún!',
    'No power translations created yet!' => 'No hay traducciones de poderes creadas aún!',
    'Power Translations' => 'Traducciones de Poderes',
    'Powers' => 'Poderes',
    'Title' => 'Título',
    'Update' => 'Actualizar',
    'View translations' => 'Ver Traducciones',
];
