<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You have earned the {super_power_name} super power!' => '¡Has ganado el super poder de {super_power_name}!',
    'Congratulations!' => '¡Felicitaciones!',
    'Are you sure you want to delete this item?' => 'Estás seguro que quieres eliminar este ítem?',
    'Create' => 'Crear',
    'Create Power Translation' => 'Crear traducción de poder',
    'Create Power Translations' => 'Crear traducciones de poder',
    'Create Powers' => 'Crear Poderes',
    'Create Quality Powers' => 'Crear poderes de cualidad',
    'Create User Powers' => 'Crear poderes de usuario',
    'Create User Qualities' => 'Crear cualidades de usuario',
    'Create new Power' => 'Crear nuevo Poder',
    'Create new Power Translation' => 'Crear nueva traducción de poder',
    'Created At' => 'Creado en',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'ID' => 'Identificación',
    'Improve Multiplier' => 'Mejorar el multiplicador',
    'Improve Offset' => 'Mejorar Compensación',
    'Language ID' => 'Identificación de idioma',
    'Level' => 'Nivel',
    'Modified At' => 'Modificado en',
    'No matching questions created yet!' => 'No existen preguntas asociadas aún!',
    'No power translations created yet!' => 'No hay traducciones de poderes creadas aún!',
    'Power ID' => 'Identificación de poder',
    'Power Translations' => 'Traducciones de Poderes',
    'Powers' => 'Poderes',
    'Quality ID' => 'Identificación de cualidad',
    'Quality Powers' => 'Poderes de cualidad',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'This user must answer psychometric questionnaire first.' => 'Este usuario debe responder el cuestionario psicométrico primero.',
    'Title' => 'Título',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Updated At' => 'Actualizada a las',
    'User ID' => 'Identidad de usuario',
    'User Powers' => 'Poderes de usuario',
    'User Qualities' => 'Cualidades de usuario',
    'Value' => 'Valor',
    'View translations' => 'Ver Traducciones',
];
