<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Change</strong> Owner' => 'strong>Cambiar</strong> Propietario',
    '<strong>General</strong> settings' => '<strong>General</strong> ajustes',
    '<strong>Security</strong> settings' => '<strong>Seguridad</strong> ajustes',
    'As owner of this space you can transfer this role to another administrator in space.' => 'Como propietario de este espacio se puede transferir esta función a otro administrador en el espacio.',
    'Color' => 'Color',
    'Space owner' => 'Propietario del espacio',
    'Transfer ownership' => 'Transferir propiedad',
];
