<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This option will show new content from this space at your dashboard' => '',
    '<i class="fa fa-cog"></i>' => '<i class="fa fa-cog"></i>',
    'Cancel Membership' => 'Cancelar Membresia',
    'General' => 'General',
    'Hide posts on dashboard' => 'Ocultar Mensaje en dashboard',
    'Members' => 'Miembros',
    'Modules' => 'Módulos',
    'Show posts on dashboard' => 'Mostrar Mensaje en dashboard',
    'This option will hide new content from this space at your dashboard' => 'Esta opción mostrará nuevos contenidos de este espacio en su dashboard',
];
