<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Chapter' => 'Capítulo',
    'Chapter ID' => 'ID de Capítulo',
    'Chapter Number' => 'Número del Capítulo',
    'Create Chapter' => 'Crear Capítulo',
    'Language' => 'Idioma',
    'Mission' => 'Misión',
    'Novel' => 'Novela',
    'Select Chapter' => 'Seleccionar Capítulo',
    'Select Language' => 'Seleccionar Idioma',
    'Select Mission' => 'Seleccionar Misión',
    'As you see, Marta\'s story continues. She, like you, is committed to transforming her community. That\'s why you have {points} points in the power of Transformation.<br><br>You have always had this power. Now it is time to discover your other hidden powers.' => 'Como ves, la historia de Marta continúa. Ella, al igual que tú, está comprometida con la creación de un cambio en su comunidad. Es por eso que tienes {points} puntos en el poder de la Transformación.<br><br>Este poder ha sido evidente en ti desde que la red te encontró. Ahora descubramos los otros poderes que tienes y que hasta ahora no han sido tan evidentes.',
    'Create' => 'Crear',
    'Create Page' => 'Crear Página',
    'Delete' => 'Borrar',
    'Discover Your Powers' => 'Descubre tus poderes',
    'Edit' => 'Editar',
    'Edit ' => 'Editar ',
    'Graphic Novel' => 'Novela',
    'ID' => 'Identificación',
    'Image' => 'Imagen',
    'No images uploaded yet' => 'No hay imágenes se han subido aún',
    'Page Image' => 'Imagen de la página',
    'Page Number' => 'Número de página',
    'Pages' => 'Páginas',
    'Update' => 'Actualizado',
    'Uploaded Image: {file}' => 'Imagen subida: {file}',
];
