<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add' => 'Añadir',
    'Add Chapter Page' => 'Añadir página de capítulo',
    'Add an existent page' => 'Añadir una página existente',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea eliminar este item?',
    'Chapter #{number}' => 'Capítulo #{number}',
    'Chapter Pages' => 'Páginas de capítulo',
    'Chapters' => 'Capítulos',
    'Create New Novel' => 'Crear nueva novela',
    'Create new page' => 'Crear nueva página',
    'Graphic Novels' => 'Novelas gráficas',
    'Leave it empty to use a image instead' => 'Dejar vacío para usar una imagen en su lugar',
    'Markup' => 'Markup',
    'No chapter page added yet!' => 'No hay página de capítulo aún!',
    'Novel #{number}' => 'Novela #{number}',
    'Page ID' => 'Identificación de Página',
    'Remove from Chapter' => 'Borrar de capítulo',
    'Select Page' => 'Seleccionar página',
    'This mission is already associated to a chapter, choose another one.' => 'Esta misión ya está asociada a un capítulo, elegir otra.',
    'View pages' => 'Ver páginas',
    'As you see, Marta\'s story continues. She, like you, is committed to transforming her community. That\'s why you have {points} points in the power of Transformation.<br><br>You have always had this power. Now it is time to discover your other hidden powers.' => 'Como ves, la historia de Marta continúa. Ella, al igual que tú, está comprometida con la creación de un cambio en su comunidad. Es por eso que tienes {points} puntos en el poder de la Transformación.<br><br>Este poder ha sido evidente en ti desde que la red te encontró. Ahora descubramos los otros poderes que tienes y que hasta ahora no han sido tan evidentes.',
    'Chapter' => 'Capítulo',
    'Chapter Number' => 'Número del Capítulo',
    'Create' => 'Crear',
    'Create Chapter' => 'Crear Capítulo',
    'Delete' => 'Borrar',
    'Discover Your Powers' => 'Descubre tus poderes',
    'Edit' => 'Editar',
    'Edit ' => 'Editar ',
    'Graphic Novel' => 'Novela',
    'ID' => 'Identificación',
    'Image' => 'Imagen',
    'Language' => 'Idioma',
    'Mission' => 'Misión',
    'No images uploaded yet' => 'No hay imágenes se han subido aún',
    'Novel' => 'Novela',
    'Page Image' => 'Imagen de la página',
    'Page Number' => 'Número de página',
    'Select Language' => 'Seleccionar Idioma',
    'Select Mission' => 'Seleccionar Misión',
    'Update' => 'Actualizado',
    'Uploaded Image: {file}' => 'Imagen subida: {file}',
];
