<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Discover Your Powers' => 'Descubre tus poderes',
    'This power has been evident since the network found you. Now we will discover the other powers you have and which so far have not been so evident.' => '',
    'You earned {points} points in Transformation' => 'Ha ganado {points} puntos en Transformación',
    'Congratulations!' => 'Felicitaciones',
    'Create' => 'Crear',
    'Create Page' => 'Crear Página',
    'Delete' => 'Borrar',
    'Edit' => 'Editar',
    'Edit ' => 'Editar ',
    'Graphic Novel' => 'Novela gráfica',
    'ID' => 'Identificación',
    'Image' => 'Imagen',
    'No images uploaded yet' => 'No hay imágenes se han subido aún',
    'Page Image' => 'Imagen de la página',
    'Page Number' => 'Número de página',
    'Pages' => 'Páginas',
    'Update' => 'Actualizado',
    'Uploaded Image: {file}' => 'Imagen subida: {file}',
    'You earned {points} points in Transformation' => '',
    'novel intro' => 'antes de empezar tu recorrido, quiero compartirte la historia de Marta. Su caso es muy valioso para entender las problemáticas que está viviendo tu comunidad. Ella será su guía y estará disponible para ayudarlos en las misiones, actividades y evokaciones.',
];
