<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer all the order questions from 1 to 4.' => '',
    'Are you sure you want to delete this item?' => '',
    'Are you sure you want to delete this quality?' => '',
    'Are you sure you want to delete this superhero identity?' => '',
    'Are you sure you want to delete this translation?' => '',
    'Choose one answer for each single-choice question.' => '',
    'Congratulations, you have ventured further than most by answering this call. 
    Now, it\'s time to find out what type of Evoke agent are you. What do you know? 
    What are the strengths, passions, and abilities you will bring to the Evoke network?
    Answer the following and find out what type of Super Hero is hiding inside you!' => '',
    'Create' => '',
    'Create Matching Question Translation' => '',
    'Create Qualities' => '',
    'Create Superhero Identity Translations' => '',
    'Create new Matching Answer' => '',
    'Create new Matching Question' => '',
    'Create new Quality' => '',
    'Create new Superhero Identity' => '',
    'Create new Translation' => '',
    'Delete' => '',
    'Description' => '',
    'ID Code' => '',
    'In case of redirect, please make sure to answer all questions' => '',
    'Language' => '',
    'Matching Answer' => '',
    'Matching Answers' => '',
    'Matching Question' => '',
    'Matching Questions' => '',
    'Name' => '',
    'No matching question translations created yet!' => '',
    'No matching questions created yet!' => '',
    'No missions created yet!' => '',
    'No qualities created yet!' => '',
    'No quality translations created yet!' => '',
    'No superhero identity created yet!' => '',
    'No superhero identity translations created yet!' => '',
    'Not Defined Yet' => '',
    'Order' => '',
    'Order questions from 1 to 4. Do not repeat numbers.' => '',
    'Primary Power' => '',
    'Primary Quality' => '',
    'Qualities' => '',
    'Secondary Power' => '',
    'Secondary Quality' => '',
    'Select Option' => '',
    'Short Name' => '',
    'Single Choice' => '',
    'Superhero Identities' => '',
    'Superhero Identity' => '',
    'Superhero Identity Translation' => '',
    'Translations' => '',
    'Update' => '',
    'Update Matching Answer' => '',
    'Update Matching Answer Translation' => '',
    'Update Matching Question Translation' => '',
    'Update Matching Questions' => '',
    'Update {modelClass}: ' => '',
    'View Matching Answers' => '',
    'View translations' => '',
];
