<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create Power Translation' => '',
    'Create Power Translations' => '',
    'Create Powers' => '',
    'Create Quality Powers' => '',
    'Create User Powers' => '',
    'Create User Qualities' => '',
    'Create new Power' => '',
    'Create new Power Translation' => '',
    'Created At' => '',
    'Delete' => '',
    'Description' => '',
    'ID' => '',
    'Image' => '',
    'Improve Multiplier' => '',
    'Improve Offset' => '',
    'Language ID' => '',
    'Level' => '',
    'Modified At' => '',
    'No images uploaded yet' => '',
    'No matching questions created yet!' => '',
    'No power translations created yet!' => '',
    'Power ID' => '',
    'Power Translations' => '',
    'Powers' => '',
    'Quality ID' => '',
    'Quality Powers' => '',
    'Reset' => '',
    'Search' => '',
    'This user must answer psychometric questionnaire first.' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Uploaded Image: {file}' => '',
    'User ID' => '',
    'User Powers' => '',
    'User Qualities' => '',
    'Value' => '',
    'View translations' => '',
];
