<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'As you can see, Marta\'s story continues. She, like you, is committed to creating change in her community. Because of your commitment you have received {points} points in the power of Transformation.<br><br>This power has been evident since the network found you. Now we will discover the other powers you have and which so far have not been so evident.' => '',
    'Congratulations!' => '',
    'Create' => '',
    'Create Page' => '',
    'Delete' => '',
    'Discover Your Powers' => '',
    'Edit' => '',
    'Edit ' => '',
    'Graphic Novel' => '',
    'ID' => '',
    'Image' => '',
    'No images uploaded yet' => '',
    'Page Image' => '',
    'Page Number' => '',
    'Pages' => '',
    'This power has been evident since the network found you. Now we will discover the other powers you have and which so far have not been so evident.' => 'You have always had this power.  Now it is time to discover your other hidden powers.',
    'Update' => '',
    'Uploaded Image: {file}' => '',
    'You earned {points} points in Transformation' => '',
    'novel intro' => 'Before begining your journey, I want to share the story of Marta with you. Her case can help you understand the problems of your own community. She will be your guide and will be available to help you in the missions, activities, and evokations to come.',
    'Graphic Novel' => '',
];
