<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'As you see, Marta\'s story continues. She, like you, is committed to transforming her community. That\'s why you have {points} points in the power of Transformation.<br><br>You have always had this power. Now it is time to discover your other hidden powers.' => '',
    'Chapter' => '',
    'Chapter ID' => '',
    'Chapter Number' => '',
    'Create' => '',
    'Create Chapter' => '',
    'Create Page' => '',
    'Delete' => '',
    'Discover Your Powers' => '',
    'Edit' => '',
    'Edit ' => '',
    'Graphic Novel' => '',
    'ID' => '',
    'Image' => '',
    'Language' => '',
    'Mission' => '',
    'No images uploaded yet' => '',
    'Novel' => '',
    'Page Image' => '',
    'Page Number' => '',
    'Pages' => '',
    'Select Chapter' => '',
    'Select Language' => '',
    'Select Mission' => '',
    'Update' => '',
    'Uploaded Image: {file}' => '',
];
