<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '1 Evocoin!' => '',
    '10 Evocoin(s)!' => '',
    '20 Evocoin(s)!' => '',
    '5 Evocoin(s)!' => '',
    '50 Evocoin(s)!' => '',
    'Create' => '',
    'Create Prize' => '',
    'Delete' => '',
    'Description' => '',
    'Discover Tools' => '',
    'Download here instructions to the boardgame.' => '',
    'Download instructions PDF' => '',
    'Edit' => '',
    'Edit ' => '',
    'Evocoin(s)' => '',
    'Evoke Tools' => '',
    'ID' => '',
    'Image' => '',
    'Located in Soacha, this game was designed by a secret team from the network to ensure countless hours of fun with your team of agents. When you play, you can win evocoins both to use the slot machine and to invest in your Evokations portfolio' => '',
    'Name' => '',
    'Not Enough Evocoin!' => '',
    'Pay 5 Evocoins to play' => '',
    'Powers' => '',
    'Prize' => '',
    'Prizes' => '',
    'Quantity' => '',
    'Slot Machine' => '',
    'The Boardgame' => '',
    'Tools remaining: {total}' => '',
    'Try your luck' => '',
    'Try your luck to win support in our slot machine. Every attempt will cost 5 evocoins.' => '',
    'Update' => '',
    'User' => '',
    'We introduce some tools the network has made available to facilitate your agent work in Soacha.' => '',
    'Week of' => '',
    'Weight' => '',
    'Won Prizes' => '',
    'weight explanation' => '',
];
