<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag a photo here or click to browse your files' => 'Arrastre una foto aquí o haga clic para navegar por los archivos',
    'Hide my year of birth' => 'Ocultar mi año de nacimiento',
    'Howdy <strong>%firstname%</strong>, thank you for using HumHub.' => 'Hola <strong>%firstname%</strong>, gracias por usar HumHub.',
    'Save and close' => 'Guardar y cerrar',
    'You are the first user here... Yehaaa! Be a shining example and complete your profile,<br>so that future users know who is the top dog here and to whom they can turn to if they have questions.' => 'Usted es el primer usuario aquí ... Yehaaa ! Sea un ejemplo brillante y completan su perfil <br>para que los futuros usuarios sepan quién es el perro superior aquí y al que pueden acudir a si tienen preguntas.',
    'Your firstname' => 'Su nombre',
    'Your lastname' => 'Tu apellido',
    'Your mobile phone number' => 'Tu número de teléfono',
    'Your phone number at work' => 'Su número de teléfono en el trabajo',
    'Your skills, knowledge and experience (comma separated)' => 'Sus habilidades, conocimientos y experiencia (separadas por comas)',
    'Your title or position' => 'Su título o cargo',
];
