<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '# of Evidences' => '# Evidencias',
    '# of Evocoins' => '# Evocoins',
    '# of Followees' => '# Siguiendo',
    '# of Followers' => '# Seguidores',
    '# of Reviews' => '# Evaluaciones',
    '% of submitted evidence for this activity' => '% de evidencias para esta actividad',
    'Activities Statistics' => 'Estadísticas de Actividades',
    'Agents: {list}' => 'Agentes: {list}',
    'Average Earned by Agents: {list}' => 'Media obtenida por los agentes: {list}',
    'Average Earned by Mentors: {list}' => 'Media obtenida por los mentores: {list}',
    'Average Number of evidences per player: {list}' => 'Media de evidencias por agente: {list^}',
    'Average by Agents: {list}' => 'Media por agentes: {list}',
    'Average by Mentors: {list}' => 'Media por mentores: {list}',
    'Average number of Evocoin per total number of Participants' => 'Media de evocoins por total de participantes',
    'Average number of reviews per evidence: {list}' => 'Media de evaluaciones por evidencía: {list}',
    'Average number of reviews received per player: {list}' => 'Media de evaluaciones por agente: {list}',
    'Average size of evidence in number of words: {list}' => 'Tamaño medio de la evidencia en número de palabras: {list}',
    'By Agents: {list}' => 'Por agentes: {list}',
    'By Mentors: {list}' => 'Por mentores: `{list}',
    'By mentors: {list}' => 'Por mentores: {list}',
    'By players: {list}' => 'Por agentes: {list}',
    'Content Creation' => 'Creación de contenido',
    'Download Report' => 'Hacer download de informe',
    'Evidences Submitted by team' => 'Evidencias postadas por equipo',
    'Evocoin Statistics' => 'Estadísticas de Evocoins',
    'Evocoin from Comments: {list}' => 'Evocoin de comentarios: {list}',
    'Evocoin from Reviews: {list}' => 'Evocoin de evaluaciones: {list}',
    'Evocoins' => 'Evocoins',
    'Has Read Novel?' => 'Ha leído novela?',
    'Mentor' => 'Mentor',
    'Mentors comments: {list}' => 'Comentarios de mentores: {list}',
    'Mentors: {list}' => 'Mentores: {list}',
    'Mission' => 'Missión',
    'Name' => 'Nombre',
    'No' => 'No',
    'Number of Comments Given' => 'Número de comentarios dados',
    'Number of Evidences: {list}' => 'Número de evidencias: {list}',
    'Number of Images Posted: {list}' => 'Número de imágenes postadas: {list}',
    'Number of Likes Given: {list}' => 'Número de likes dados: {list}',
    'Number of Reviews' => 'Número de evaluaciones',
    'Number of Spaces Created: {list}' => 'Número de espacios: {list}',
    'Number of Status Updates (Posts): {list}' => 'Número de actualizaciones de status (posts): {list}',
    'Number of Teams: {list}' => 'Número de equipos: {list}',
    'Number of Videos Posted: {list}' => 'Número de vídeos postados: {list}',
    'Number of comments/user: {list}' => 'Número de comentarios por usuario: {list}',
    'Number of evidences' => 'Número de evidencias',
    'Participation' => 'Participación',
    'Player comments: {list}' => 'Comentarios de jugadores: {list}',
    'Reviews' => 'Evaluaciones',
    'Slot Machine' => 'Máquina Tragamonedas',
    'Slot Machine Evocoin Created: {list}' => 'Máquina Tragamonedas: {list}',
    'Slot Machine Uses: {list}' => 'Usos de Máquina Tragamonedas: {list}',
    'Space Statistics' => 'Estadísticas de Espacios',
    'Statistics Overview' => 'Estadísticas Gerais',
    'Statistics Reports' => 'Reportes de Estadísticas',
    'Total Number Earned by Agents: {list}' => 'Total ganado por agentes: {list}',
    'Total Number Earned by Mentors: {list}' => 'Total ganado por mentores: {list}',
    'Total Number of Evocoins Created: {list}' => 'Total ganado por evocoins creadas: {list}',
    'Total Number of Evocoins: {list}' => 'Total de evocoins: {list}',
    'Total Number of Users: {list}' => 'Total de usuarios: {list}',
    'Total Users on each team' => 'Total de usuarios en cada espacío',
    'Total number of comments provided' => 'Total de commentarios',
    'Total number of evidences: {evidences}' => 'Total de evidencias: {evidences}',
    'Total reviews by team' => 'Total de evaluaciones por equipo',
    'User' => 'Usuario',
    'User Statistics' => 'Estadísticas de usuario',
    'User or Mentor' => 'Usuario o mentor',
    'Username' => 'Nombre de usuario',
    'Yes' => 'Sí',
];
