<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '# of Evidences' => '',
    '# of Evocoins' => '',
    '# of Followees' => '',
    '# of Followers' => '',
    '# of Reviews' => '',
    '% of submitted evidence for this activity' => '',
    'Activities Statistics' => '',
    'Agents: {list}' => '',
    'Average Earned by Agents: {list}' => '',
    'Average Earned by Mentors: {list}' => '',
    'Average Number of evidences per player: {list}' => '',
    'Average by Agents: {list}' => '',
    'Average by Mentors: {list}' => '',
    'Average number of Evocoin per total number of Participants' => '',
    'Average number of reviews per evidence: {list}' => '',
    'Average number of reviews received per player: {list}' => '',
    'Average size of evidence in number of words: {list}' => '',
    'By Agents: {list}' => '',
    'By Mentors: {list}' => '',
    'By mentors: {list}' => '',
    'By players: {list}' => '',
    'Content Creation' => '',
    'Download Report' => '',
    'Evidences Submitted by team' => '',
    'Evocoin Statistics' => '',
    'Evocoin from Comments: {list}' => '',
    'Evocoin from Reviews: {list}' => '',
    'Evocoins' => '',
    'Has Read Novel?' => '',
    'Mentor' => '',
    'Mentors comments: {list}' => '',
    'Mentors: {list}' => '',
    'Mission' => '',
    'Name' => '',
    'No' => '',
    'Number of Comments Given' => '',
    'Number of Evidences: {list}' => '',
    'Number of Images Posted: {list}' => '',
    'Number of Likes Given: {list}' => '',
    'Number of Reviews' => '',
    'Number of Spaces Created: {list}' => '',
    'Number of Status Updates (Posts): {list}' => '',
    'Number of Teams: {list}' => '',
    'Number of Videos Posted: {list}' => '',
    'Number of comments/user: {list}' => '',
    'Number of evidences' => '',
    'Participation' => '',
    'Player comments: {list}' => '',
    'Reviews' => '',
    'Slot Machine' => '',
    'Slot Machine Evocoin Created: {list}' => '',
    'Slot Machine Uses: {list}' => '',
    'Space Statistics' => '',
    'Statistics Overview' => '',
    'Statistics Reports' => '',
    'Total Number Earned by Agents: {list}' => '',
    'Total Number Earned by Mentors: {list}' => '',
    'Total Number of Evocoins Created: {list}' => '',
    'Total Number of Evocoins: {list}' => '',
    'Total Number of Users: {list}' => '',
    'Total Users on each team' => '',
    'Total number of comments provided' => '',
    'Total number of evidences: {evidences}' => '',
    'Total reviews by team' => '',
    'User' => '',
    'User Statistics' => '',
    'User or Mentor' => '',
    'Username' => '',
    'Yes' => '',
];
