<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'As a mentor you can offer your time to the agents to help with their projects, activities, or offer guidance.' => '',
    'Bought Products' => '',
    'Buy' => '',
    'Click to mark as fulfilled' => '',
    'Create' => '',
    'Delete' => '',
    'Description' => '',
    'Edit' => '',
    'Edit ' => '',
    'Evocoin(s)' => '',
    'Fulfill' => '',
    'Fulfilled?' => '',
    'ID' => '',
    'Image' => '',
    'Marketplace' => '',
    'Mentoring' => '',
    'Name' => '',
    'No' => '',
    'No images uploaded yet' => '',
    'Offer your time' => '',
    'Offer your time!' => '',
    'Please describe the nature of the mentoring offered:' => '',
    'Powers' => '',
    'Price' => '',
    'Product' => '',
    'Product ID' => '',
    'Products' => '',
    'Quantity' => '',
    'Sold Out' => '',
    'Sorry you do not have enough evocoin!' => '',
    'Sorry, something went wrong with your purchase' => '',
    'Time' => '',
    'Unfulfill' => '',
    'Update' => '',
    'Uploaded Image: {file}' => '',
    'User' => '',
    'Fulfill' => '',
    'Bought Time' => '',
    'Bought Products' => '',
    'Unfulfilled Products' => '',
    'Fulfilled Products' => '',
    'return' => '',
    "You successfully returned {product}!" => '',
    'Sorry, something went wrong with your return' => '',
    'You successfully fulfilled time for {username}!' => '',
    'User ID' => '',
    'Week of' => '',
    'Yes' => '',
    'You successfully bought {product}!' => '',
    'in minutes' => '',
];
