<?php

use yii\helpers\Html;

?>

<style media="screen">

  <?php if (!Yii::$app->user->getIdentity()->has_read_novel && Yii::$app->user->getIdentity()->group->name != "Mentors"): ?>
    .topbar, .footer {
      display: none;
    }

    body {
      padding-top: 1em;
    }
  <?php endif; ?>
  
</style>

<h4 style="background-color: #101C2A; text-align: center; padding: 10px 0; margin: 0px 0 20px; color: #5aa2c6;"><?php echo Yii::t('StaticsModule.base', 'Terms and Conditions of Use & Privacy Policy') ?></h4>

<p style="margin:0 150px">

    Terms and Conditions of Use & Privacy Policy<br><br>

    International Bank for Reconstruction and Development (The “World Bank”) maintains this web site (the "Site") as a courtesy to those who may choose to access the Site ("Users"). These Terms and Conditions of Use & Privacy Policy, including any guidelines and future modifications (collectively the "Terms and Conditions" or “Agreement”) govern the use of this Site and is a legal contract between Users and The World Bank as outlined below. User is fully able and competent to enter into these Terms and Conditions.  If User is accessing the Site as a representative of a legal entity, User represents that s/he has the authority to enter into this Agreement on behalf of that entity and agrees that the term “User” refers to that entity.<br><br>

    By registering with us or using or browsing the Site, User acknowledges that he has read, understood, and agrees to be bound by this Agreement. If User does not agree to these Terms and Conditions, User can stop using the Site at any time.<br><br>

    The Site is not directed to children younger than 13 and is offered only to Users 13 years of age or older. If you are under 13 years old, please do not use the Site.<br><br>

    General Terms and Conditions.<br><br>
    1. The World Bank is pleased to allow Users, subject to these Terms and Conditions, and also subject to more specific restrictions that may apply to specific material within this Site, to visit the Site and: (i) download and copy the information, documents and materials (collectively, "Materials") from the Site for the User's personal, non-commercial use, without any right to resell, redistribute or create derivative works there from; (ii) to use the blogs, bulletin boards, chat rooms, access to mailing lists, interactive games or other social media (collectively, "Interactive Tools"); (iii) upload or link comments, recommendations, forums, photos, videos, music, sounds, images, text, files, listings, logos, trademarks, postings, messages, tags and other content or material (collectively “Content”) through the Interactive Tools that may be available on this Site. Some Interactive Tools and other applications of the Site may: (i) ask the User to register and provide personal information such as name, gender, city, email address, school, work, employer or organizational affiliation, country of citizenship or residence according to Section 16 (the “Personal Information”); (ii) require the User to post information or allow the User to create new products through the interaction with interactive games such as the Evoke Game (the information required by the Interactive Tools and the new products created through the interaction with interactive games will be collectively referred to as “Posted Information” and, jointly with Personal Information, as the “Information”). Users are not allowed to collect product or service listings or descriptions displayed here, and are not allowed to perform any derivative use of this Site or the Materials for the benefit of a third party.<br>
    2. The World Bank is a member of The World Bank Group, which is comprised of IBRD (International Bank for Reconstruction and Development); IDA (International Development Association); IFC (International Finance Corporation); MIGA (Multilateral Guarantee Agency); and ICSID (International Centre for Settlement of Investment Disputes). All Material on this Site from the various members of The World Bank Group, and other content providers, appears on this Site subject to these Terms and Conditions. In addition, the members of The World Bank Group and such content providers may have additional terms and conditions that govern the use of their material.<br> 
    3. Unless expressly stated otherwise, the findings, interpretations, and conclusions expressed in the Materials in this Site are those of the various authors of the work and are not necessarily those of The World Bank Group's Boards of Executive Directors or its member countries.<br><br>

    Disclaimers, Limitations on Warranties and Representations, and Waivers.<br><br>

    4. Materials provided on this site are provided "as is" and “as available” without warranty of any kind. The World Bank and its successors, affiliates, contractors, employees, suppliers, licensors, partners and agents expressly disclaim all representations, warranties, or conditions of any kind, whether express or implied, including, but not limited to, the implied warranties or conditions of merchantability, fitness for a particular purpose, accuracy, completeness, performance, system integration, quiet enjoyment, title, and non-infringement. The World Bank specifically does not make any warranties or representations as to any third-party Content accessible via an Internet link or any Content posted by the User or by any third party. The World Bank disclaims any warranty that the Site, Content and Materials will meet your requirements or be uninterrupted, timely, secure, or error-free, that defects will be corrected, or that the Site or the server that makes the Site available is free of viruses or other harmful components. The World Bank makes no guarantee regarding (a) the amount, timing and delivery of any clicks or impressions with respect to any Material or Content or advertising on the Site.
    The World Bank does not ensure that User Information and Content will not be lost, misused, forged, destroyed, intercepted, targeted in a cyber attack or subject to unauthorized access, disclosure or modification,. The World Bank takes no responsibility, and assumes no liability for any Information or Content posted by the User or any third party on the Site. The World Bank periodically adds, changes, improves, or updates the Materials on this Site without notice.<br>
    The World Bank assumes no responsibility for monitoring the Site for inappropriate Content or conduct. If at any time The World Bank chooses, in its sole discretion to monitor the Site, The World Bank nonetheless assumes no responsibility for the Content of the Site, no obligation to modify or remove any inappropriate Content, and no responsibility for the conduct of the User submitting any such Content.<br>
    Use of this Site is at User's sole risk. Under no circumstances shall The World Bank , any other member of The World Bank Group, or any other content provider, be liable for any loss, damage, liability or expense incurred or suffered which is claimed to result from use of or in connection with any activity in relation to this Site, or as a result of the transmission or disclosure of confidential or partially disclosed Content or Information (including, without limitation, anything (including any tools made available through this Site) that may personally identify the User or the User’s location) through the access to or use of this Site or any Interactive Tool or otherwise provided thereby, including without limitation, any fault, error, omission, interruption or delay with respect thereto as well as any loss, misuse, unauthorized access, disclosure, unauthorized distribution, modification or destruction of Content or Information provided or transmitted by User or forging of User’s e-mail.<br>
    Under no circumstances or legal theory, including, but not limited to, negligence, shall The World Bank or any member of the World Bank Group, its Board of Executive Directors, donors, contractors, employees, or any other content provider, be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including, but not limited to, damages for loss of profits, cost of cover, goodwill, use, data, or other intangible losses (even if The World Bank has been advised of the possibility of such damages), arising from or relating to this Agreement or the use or the inability to use the Site. No advice or information, whether oral or written, obtained by the User from The World Bank or through or from the Site shall create any warranty not expressly stated in these Terms and Conditions.<br>
    5. User specifically represents and warrants that, when accessing the Site: (i) User is 13 years of age or older; (ii) User will comply with all local, state, national and international laws, regulations, judicial or governmental orders and treaties that are applicable in the jurisdiction where the User is domiciled and/or accesses the Site (collectively “the Jurisdiction Laws”); (iii) User is solely responsible for any violation of the Jurisdiction Laws.<br>
    6. User specifically acknowledges and agrees that The World Bank is not liable for any conduct of any User, including but not limited to violation of the Jurisdiction Laws. In this regard, User is solely responsible and liable for all actions, activities, acts and omissions taken via the User’s member account, User name and/or password, whether or not made with User’s knowledge or authority.<br>
    7. User specifically acknowledges and agrees that nothing in any agreement (or related policies) User may be subject to with any network creator or other party will alter, impair, supersede, amend or otherwise affect in any way any terms of this Agreement or any guidelines related thereto.<br>
    8. User represents and warrants that: (i) he owns or otherwise controls all the rights to the Information and Content uploaded or linked to his member account or through any Interactive Tool; (ii) he has the right to grant the license set forth in Section 24; (iii) the Information and Content uploaded or linked to his member account or through any Interactive Tool are accurate; (iv) by the supply of the Information and Content to The World Bank, User does not violate this Policy and does not infringe the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity; (v) he agrees to pay for all royalties, fees, and any other monies owing to any person or entity by reason of any Content uploaded or linked to his member account or through any Interactive Tool.<br>
    9. This site may contain advice, opinions, and statements of various content providers. The World Bank does not represent or endorse the accuracy or reliability of: (i) any advice, opinion, statement or Materials provided by any information provider or content provider; (ii) any Content or Information provided by any User of this site or other person or entity. Reliance upon any such opinion, advice, statement, Material, Content or Information shall also be at User’s own risk. Neither The World Bank nor its affiliates, nor any of their respective agents, employees, information providers or content providers shall be liable to any User or anyone else for any inaccuracy, error, omission, interruption, timeliness, loss, misuse, unauthorized access, disclosure, unauthorized distribution, destruction, completeness, deletion, defect, failure of performance, computer virus, communication line failure, alteration of, or use of any Content or Information herein, regardless of cause, for any damages resulting there from.<br>
    10. As a condition of use of this Site, User agrees to indemnify The World Bank, other members of The World Bank Group, its affiliates, and all content providers from and against any and all actions, claims, losses, damages, liabilities and expenses (including reasonable attorneys' fees) arising out of User's use of this Site, including without limitation any claims alleging facts that if true would constitute a breach by User of these Terms and Conditions. If User is dissatisfied with any material on this Site or with any of terms and conditions of use of this Site, User's sole and exclusive remedy is to discontinue using this Site.<br>
    11. Nothing in this Site or any Materials shall be construed, implicitly or explicitly, as containing any investment recommendations. The World Bank is not registered under the U.S. Investment Advisers Act of 1940. Accordingly, nothing in such Site, or in such Materials, constitutes an offer of or an invitation by or on behalf of The World Bank to purchase or sell any shares or securities nor should it be considered as investment advice.<br>
    12. User may elect in User’s sole and exclusive discretion to act or take part in activities in public settings, as well as interacting with other players and/or the general public in order to participate in some interactive games contained in this Site. User specifically acknowledges and agrees that any such actions or activities performed as a part of the interactive games, including but not limited to taking part in activities in public settings and interacting with other players or the general public before, during, or after the game, are performed entirely and exclusively at User’s own risk. User specifically acknowledges and agrees that User may elect not to participate in the interactive games at any time, including any actions or activities in public settings or interaction with other players.<br><br>

    Links to third-party web sites and use of Interactive Tools<br><br>
    13. This Site contains links to third-party web sites. The linked sites are not under the control of The World Bank and The World Bank is not responsible for the Contents of any linked site or any link contained in a linked site. The World Bank provides these links only as a convenience, and the inclusion of a link does not imply endorsement of the linked site by The World Bank.<br>
    14. This Site may contain Interactive Tools. User specifically acknowledges and agrees that he is solely responsible for the Content that he uploads or links to his member account and transmits to other Users through the Interactive Tools as well as for his interactions with other Users. User agrees to use the Interactive Tools only to send, receive and post messages and material that are proper and related to the particular content area. By way of example, and not as a limitation, User agrees that when using an Interactive Tool, User shall not do any of the following:<br>
    · Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.<br>
    · Publish, post, distribute or disseminate any defamatory, infringing, obscene, indecent or unlawful Content.<br>
    · Upload or attach files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless User owns or controls the rights thereto or has received all necessary consents.<br>
    · Upload or attach files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another's computer.<br>
    · Delete any author attributions, legal notices or proprietary designations or labels in any file that is uploaded.<br>
    · Falsify the origin or source of software or other material contained in a file that is uploaded.<br>
    · Advertise or offer to sell any goods or services, or conduct or forward surveys, contests, or chain letters. Download any file posted by another User of a Forum that you know, or reasonably should know, cannot be legally distributed in such manner.<br>
    · Create a false identity for the purpose of misleading others.<br>
    · Disrupt the normal flow of communities or negatively affects other Users' ability to participate in communities.<br>
    · Contact anyone who has asked not to be contacted or “stalk" or otherwise harass anyone.<br>
    · Violate any Jurisdiction Laws.<br>
    · Violate or infringe upon any intellectual property rights, rights of publicity or privacy or any other rights of The World Bank or of any other person.<br>
    · Gain unauthorized access to the Site, other Users' member accounts, names, passwords, personally identifiable information or other computers, websites or pages, connected or linked to the Site or use the Site in any manner which violates or is inconsistent with these Terms and Conditions.<br>
    · Modify, disrupt, impair, alter or interfere with the use, features, functions, operation or maintenance of the Site or the rights of use and enjoyment of the Site by any other person.<br>
    · Constitute or promote Information or Content that User knows is false or misleading, furthers or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous.<br>
    · Transmit "junk mail," "chain letters," or unsolicited mass mailing, instant messaging, "spimming," or "spamming".<br>
    · Post Information or Content that includes restricted or password only access pages or hidden pages or images (those not linked to or from another accessible page).<br>
    · Solicit or collect personal data including telephone numbers, addresses, last names, email addresses, passwords or personal identifying information from other Users or other third parties.<br>
    · Promote commercial activities and/or sales without prior written consent from The World Bank such as contests, sweepstakes, barter, advertising, or pyramid schemes.<br>
    · Include a photograph or video of another person without that person's consent.<br>
    · Knowingly communicate with any User under the age of 13 or communicates in an inappropriate manner with other User.<br>
    · Circumvent or modify, attempt to circumvent or modify, or encourage or assist any other person in circumventing or modifying any security technology or software that is part of the Site.<br>
    · Perform any automated use of the system, such as, but not limited to, using scripts to add friends or send comments or messages.<br>
    · Use the member account, User name, or password of other User at any time or disclose his password to any third party or permit any third party to access his member account.
    · Sell or otherwise transfer his member account or User name.<br>
    · Use the Site in a manner inconsistent with these Terms and Conditions or with any applicable laws and regulations.<br>
    15. Some aspects of use of this Site, including without limitation use of certain Interactive Tools are governed by Rules for playing Evoke (“Rules”) attached to and hereby incorporated by reference to these Terms and Conditions. User understands, acknowledges and agrees that as a condition to use, User will abide by the Rules, as amended from time to time. If User does not wish to be bound by the Rules, User may not use, access, display, download and/or otherwise copy or distribute Content obtained through that Interactive Tool.<br> 
    16. User acknowledges that exchanges on Interactive and Social Media Tools are public and not private communications. Further, User acknowledges that chats, postings, conferences, e-mails and other communications by other Users are not endorsed by The World Bank, and such communications shall not be considered reviewed, screened, or approved by The World Bank. The World Bank reserves the right for any reason to edit and remove without notice any Contents of the Interactive Tools received from Users, including without limitation e-mail, blog comments, and bulletin board postings.<br><br>

    Privacy Policy.<br><br>

    17. Registration. Some Interactive Tools require the User to register and have a unique member account, with a User name and password combination according to Section 22, in order to access and use certain features or functions of the Site. To register, the User will be asked for Personal Information. Except as specifically provided for in the Site or herein, the Personal Information provided is only used for technical and customer administration and evaluation of the Site and may be shared with third parties only for these purposes. Examples of this type of data include statistics on which pages are most popular and which are least popular. The data collected is not intended to be traced back to a particular individual/User. The purpose of this data collection is so that The World Bank can better understand the preferences of its visitors and improve this Site and its services. In this regard, the User grants The World Bank a right to use the data collected according to Section 24.<br>
    Notwithstanding, registering on this Site is optional. If User chooses not to register or provide Personal Information, User can still use the Site. However, User will not be able to use some Interactive Tools such as the interactive games, nor be able to receive certain communications such as emails and newsletters, for example.<br>
    If User chooses to use any Interactive Tool that requires registering or provision of Personal Information, part of User’s Personal Information such as e-mail address, gender, city, country, school, work, employment or organizational affiliation may be published, translated, distributed, displayed and in general be available to other Users registered on the Site.<br>
    User is entitled to cancel his member account anytime as provided in Section 25.<br>
    18. Use of cookies. When User registers on the Site, the Site sets a cookie on the User’s computer's hard drive that enables User to manage his subscriptions and online profile. By setting this cookie, the Site will remember User the next time User visits and won't have to bother User by asking questions User has already answered (like address information). However, User is always free to decline our cookies if User’s browser permits, although in that case User may not be able to use certain features and may be required to re-enter information more frequently to use certain services on the Site.<br> 
    19. IP Addresses. The Site records User’s IP address and data such as browser type and operating system. This data helps us learn about the geographical distribution of our Site visitors and the technology they use to access our Site. This data is not connected with the Personal Information User supplies in connection with registration on the Site, except in certain cases of managing errors, in which case, the contents of the http request are captured when there is an error, which is used for troubleshooting.<br> 
    20. Security. The Site employs a range of technologies to protect the data maintained on our systems. Despite such undertaking, it is possible for Internet-based communications to be intercepted, subject to unauthorized access, lost, misused, disclosed, modified, forged, destroyed or targeted by cyber attacks. Therefore, as stated in Section 4, The World Bank cannot ensure that User Content and Information will not be intercepted, subject to unauthorized access, lost, misused, disclosed, modified, destroyed, or targeted by cyber-attack.<br>
    21. Security Notice. The World Bank reserves the right but not the obligation to monitor any Content, where posted on this Site. For Site security purposes and to ensure that this service remains available to all Users, this computer system employs software programs to monitor network traffic to identify unauthorized attempts to upload or change Content or Materials, or otherwise cause damage. Unauthorized attempts to upload Content or change Content or Materials on this service are strictly prohibited and may be punishable by law. If monitoring reveals evidence of possible criminal activity, such evidence may be provided to law enforcement personnel.<br>
    22. User Names and Passwords. Member accounts, User names and passwords are personal to each User. Users shall not allow any others to use their member account, User name or password under any circumstances. Each User is responsible for guarding his password carefully with the full awareness that a failure to keep his password secure will enable others to engage in transactions for which the User will be legally responsible. Users shall notify immediately The World Bank according to Section 30 if they become aware of or believe there is or may have been any unauthorized use of (or activity using) their member account, User name or password or any other need to deactivate their member account, User name or password due to security concerns.<br><br>

    Copyrights and Content posted by User.<br><br>

    23. The material contents of this web site are copyright protected under United States and International Laws. Unauthorized use of the material content is strictly prohibited.<br> 
    24. User grants The World Bank a non-exclusive, worldwide, royalty-free, perpetual, irrevocable, fully sub-licensable and transferable right to use, reproduce, modify, delete, adapt, publish, translate, create derivative works from, distribute, perform and display such Posted Information throughout the world in any media. User grants The World Bank the right to use the name that User submits in connection with such Posted Information, if The World Bank chooses. User grants The World Bank a non-exclusive, worldwide, royalty-free, perpetual, irrevocable, fully sub-licensable and transferable right to publish, translate, distribute and display part of his Personal Information according to Section17. User hereby agrees that if his Posted Information is removed from the Site, The World Bank shall retain the rights provided below.<br>
    The World Bank may choose to use Information and Content to compile profiles for statistical purposes and may choose to trade with such profiles and statistical data, as long as the profiles or statistical data cannot be linked to any specific data subject, including User, by a third party.<br>
    The World Bank does not claim any ownership rights to the Content that User uploads or links to his/her member account using the Site.<br>
    25. Term. This Agreement shall remain in full force and effect unless and until User member account is terminated as provided herein. User is entitled to remove his Content, Posted Information and cancel his/her member account at any time. In this case, The World Bank retains the license rights as provided in Section24.<br><br>

    Applicable Jurisdiction<br><br>
    26. Any dispute or difference involving The World Bank arising out of, or in connection with, the Site or the use of the Site which cannot be amicably settled between the parties to such dispute shall be arbitrated in accordance with the Commercial Arbitration Rules of the American Arbitration Association then in effect by one arbitrator appointed in accordance with those rules. The arbitration shall take place in the District of Columbia. Any resulting arbitration decision shall be final and binding on both parties. Judgment upon any arbitration award in favor of The World Bank may be entered in any court having jurisdiction thereof.<br><br>
    Preservation of Immunities<br><br>
    27. Nothing herein shall constitute or be considered to be a limitation upon or a waiver of the privileges and immunities of the World Bank, which are specifically reserved.
    General<br>

    28. The World Bank reserves its exclusive right in its sole discretion to:<br>
    · alter, limit or discontinue the site or any Materials or Content in any respect. The World Bank shall have no obligation to take the needs of any User into consideration in connection therewith;<br>
    · to delete, disable, deactivate or terminate member accounts, remove or edit Materials or Content, cancel services, block User’s email, IP address, or otherwise terminate User’s access to or use of this Site or any portion thereof in its sole discretion and without notice;<br>
    · shut down the Site or any Interactive Tool, with or without notice, and with no liability of any kind to User; or<br>
    · change, alter or amend these Terms and Conditions of Use and Privacy Statement at any time, without notice to any User.<br>

    29. No waiver by The World Bank of any provision of this Agreement shall be binding except as set forth in a writing signed by its duly authorized representative.<br>

    30. If you have any questions or concerns about these Terms and Conditions or you want to give notice according to Section 21, please contact us at evokenet@gmail.com.

</p>

<div style="text-align:right; margin: 10px 40px">
<?php echo Html::a(
    Yii::t('StaticsModule.base', 'Next'),
    [$next_page_link], array('class' => 'btn btn-lg btn-cta1', 'style' => 'padding: 0 80px')); ?>
</div>