<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activities' => '',
    'Activity' => '',
    'Activity Powers' => '',
    'Activity {activity}' => '',
    'Activity:' => '',
    'Add new Power' => '',
    'Are you sure you want to delete this activity?' => '',
    'Are you sure you want to delete this mission?' => '',
    'Are you sure you want to delete this power?' => '',
    'Are you sure you want to delete this translation?' => '',
    'Choose Mission' => '',
    'Choose an Activity:' => '',
    'Choose how many points you will award this evidence.' => '',
    'Close' => '',
    'Congratulations!' => '',
    'Create' => '',
    'Create an Evidence for this Activity:' => '',
    'Create new Activity' => '',
    'Create new Mission' => '',
    'Create new Translation' => '',
    'Delete' => '',
    'Description' => '',
    'Distribute points for {title}' => '',
    'Edit' => '',
    'Enter Activity' => '',
    'Enter Mission' => '',
    'For every piece of evidence you review, you receive 10 points in {title}' => '',
    'How many points will you award this evidence?' => '',
    'ID Code' => '',
    'Language' => '',
    'Mission' => '',
    'Mission {mission}: Activities' => '',
    'Mission:' => '',
    'Mission: {alias}' => '',
    'Missions' => '',
    'Missions Module Configuration' => '',
    'No activities created yet!' => '',
    'No activity powers created yet!' => '',
    'No activity translations created yet!' => '',
    'No mission translations created yet!' => '',
    'No missions created yet!' => '',
    'Nothing here.' => '',
    'Please, Answer yes or no.' => '',
    'Points' => '',
    'Primary Power' => '',
    'Reset' => '',
    'Review' => '',
    'Search' => '',
    'Secondary Power' => '',
    'Select Difficulty Level' => '',
    'Select Language' => '',
    'Select Mission' => '',
    'Select Option' => '',
    'Select Power' => '',
    'Submit Review' => '',
    'Title' => '',
    'Translation' => '',
    'Translations' => '',
    'Type (Primary/Secondary)' => '',
    'Unavailable - Rate Evidence' => '',
    'Unavailable - Read Missions' => '',
    'Update' => '',
    'Update Activity' => '',
    'Update Mission' => '',
    'Update Translation' => '',
    'View' => '',
    'View Activities' => '',
    'View Powers' => '',
    'View Translations' => '',
    'View translations' => '',
    'You just gained' => '',
    'You just gained 10 points in {message}' => '',
    'Your review was updated!' => '',
    'and' => '',
    '{message}. <BR>Thank you for your review.' => '',
];
