<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new Power' => 'Añadir nuevo Poder',
    'Are you sure you want to delete this power?' => 'Está seguro que quiere eliminar este poder?',
    'Create Quality Powers' => 'Crear Poderes de Cualidad',
    'No quality powers created yet!' => 'No hay poderes de cualidad creados aún!',
    'Quality' => 'Cualidad',
    'Quality Powers' => 'Poderes de Cualidad',
    'Select Power' => 'Seleccionar Poder',
    'Title' => 'Título',
    'View Powers' => 'Ver Poderes',
    'Answer all the order questions from 1 to 4.' => 'Responde a todas las preguntas de la orden de 1 a 4',
    'Answer the following and find out what type of Super Hero is hiding inside you!' => 'Responde a la siguiente y averigua qué tipo de superhéroe que se esconde dentro de ti!',
    'Are you sure you want to delete this item?' => 'Está seguro que quiere eliminar este item?',
    'Are you sure you want to delete this quality?' => 'Está seguro que quiere eliminar esta cualidad?',
    'Are you sure you want to delete this superhero identity?' => 'stá seguro que quiere eliminar esta identidad de super héroe?',
    'Are you sure you want to delete this translation?' => 'Está seguro que quiere eliminar esta traducción?',
    'Choose one answer for each single-choice question.' => 'Elija una respuesta para cada pregunta de selección simple',
    'Congratulations, you have ventured further than most by answering this call.' => 'Felicitaciones, ha aventurado más allá de la mayoría de responder a esta llamada.',
    'Create' => 'Crear',
    'Create Matching Answer Translation' => 'Crear nueva Traducción de Respuesta Asociada',
    'Create Matching Question Translation' => 'Crear la Traducción de la pregunta asociada',
    'Create Qualities' => 'Crear Cualidades',
    'Create Superhero Identity Translations' => 'Crear Traducciones de Identidad de Superhéro',
    'Create new Matching Answer' => 'Crear nueva Respuesta Asociada',
    'Create new Matching Question' => 'Crear nueva Pregunta Asociada',
    'Create new Quality' => 'Crear nueva Cualidad',
    'Create new Superhero Identity' => 'Crear nueva Identidad de Superhéroe',
    'Create new Translation' => 'Crear nueva Traducción',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'ID Code' => 'Código ID',
    'In case of redirect, please make sure to answer all questions' => 'En caso de redirección, por favor asegúrese de responder a todas las preguntas',
    'Language' => 'Idioma',
    'Matching Answer' => 'Respuesta Asociada',
    'Matching Answers' => 'Respuestas Asociadas',
    'Matching Question' => 'Pregunta Asociada',
    'Matching Questions' => 'Preguntas Asociadas',
    'Name' => 'Nombre',
    'No matching question translations created yet!' => 'No existe traducción para las preguntas asociadas aún!',
    'No matching questions created yet!' => 'No existen preguntas asociadas aún!',
    'No missions created yet!' => 'No hay Misiones creadas aún!',
    'No qualities created yet!' => 'No hay Cualidades creadas aún!',
    'No quality translations created yet!' => 'No hay traducciones para las cualidades creadas aún!',
    'No superhero identity created yet!' => 'No hay una identidad de Superhéroe creada aún!',
    'No superhero identity translations created yet!' => 'No hay traducciones de la identidad de Superhéroe creadas aún!',
    'Not Defined Yet' => 'Aún sin definir',
    'Now, it is time to find out what type of Evoke agent are you. What do you know?' => 'Ahora, es el momento de descubrir qué tipo de agente Evoque es usted . ¿Que sabes?',
    'Order' => 'Ordenar',
    'Order questions from 1 to 4. Do not repeat numbers.' => 'Ordene esas preguntas de 1 a 4. No repetir los números',
    'Primary Power' => 'Poder Primario',
    'Primary Quality' => 'Cualidad Primaria',
    'Qualities' => 'Cualidades',
    'Qualities:' => 'Cualidades:',
    'Secondary Power' => 'Poder Secundario',
    'Secondary Quality' => 'Cualidad Secundaria',
    'Select Option' => 'Seleccionar opción',
    'Short Name' => 'Nombre Corto',
    'Single Choice' => 'Selección Simple',
    'Submit' => 'Enviar',
    'Superhero Identities' => 'Identidades de Superhéroe',
    'Superhero Identity' => 'Identidad de Superhéroe',
    'Superhero Identity Translation' => 'Traducción de Identidad de Superhéroe',
    'Translations' => 'Traducciones',
    'Update' => 'Actualizar',
    'Update Matching Answer' => 'Actualizar Respuesta Asociada',
    'Update Matching Answer Translation' => 'Actualizar Traducción de Respuesta Asociada',
    'Update Matching Question Translation' => 'Actualizar Traducción de Pregunta Asociada',
    'Update Matching Questions' => 'Actualizar Preguntas Asociadas',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'View Matching Answers' => 'Ver Respuestas Asociadas',
    'View translations' => 'Ver traducciones',
    'What are the strengths, passions, and abilities you will bring to the Evoke network?' => '¿Cuáles son las fuerzas, pasiones, habilidades que traerá a la red Evoke?',
    'Your Superhero Identity is:' => 'Su Identidad de Superhéroe es:',
];
