<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'By discovering your natural powers, you can learn how to fit into the Evoke network. 
                    Try to imagine vividly what would you do in each of the scenarios described and honestly answer each question.
                    ' => 'Al descubrir tus poderes naturales, podré saber cómo encajas en la red Evoke. Trata de imaginar vívidamente qué harías en cada uno de los escenarios descritos y de responder honestamente cada pregunta.',
    'Welcome to the Evoke network.
            <br><br>Over the next 16 weeks you will be asked to respond to the urgent challenge of forced displacement and peace in your country.  You have been selected because of your unique potential to change the world.  You have some powers there is no doubt, but you will need to increase your powers to realize your potential.  I\'ve asked one of our best agents -- Marta -- to share her story and guide you on this journey.
            <br><br>Over the course of these 16 weeks you will form a team to create your unique world changing idea or as we call it in the Evoke network -- your Evokation.  Your Evokation will be created as you respond to the 8 missions I will give you.  At the end of the journey, the network will invest evocoin in your Evokations. The 10 Evokations with the most investment will be reviewed by experts in my network and the top 3 will receive recognition and reward.  As a team you must complete all 6 activities for each mission to advance to the next mission.  By completing activities, your powers will increase.
            <br><br>There are 16 unique powers that you can develop which will in turn will give you your superpowers -- creative visionary, deep collaborator, systems thinker, and empathetic activist.  These powers will help you on your journey.
            <br><br>You will also earn Evocoin -- the currency of the Evoke network -- each time you contribute to the quality of our collective thought by giving power to others and commenting on their contributions.  Evocoin will be used at the end of your journey to invest in those world changing ideas that you think will have the greatest impact on your community, your country, the world.
            <br><br>You will also be given opportunities during the 16 weeks to exchange your Evocoin for assistance in completing your Evokation by accessing Evoke tools - transportation, materials, and other forms of support will be provided....for a cost.
            <br><br>Good luck agents. I look forward to checking in on your progress and recognizing your final Evokations at the end of this journey.' => 'Bienvenido a la red Evoke. 
            <br><br>Dentro de las próximas 16 semanas deberás dar respuesta al urgente desafío que es el desplazamiento forzado en tu país. Has sido seleccionado por tu potencial único para cambiar el mundo. Sin duda alguna, tu ya tienes poderes, pero necesitarás incrementar los mismos para alcanzar tu gran potencial. Le he pedido a uno de nuestros mejores agentes, Marta, que comparta su historia y que te guíe en este viaje.
<br><br>En el transcurso de estas 16 semanas, formarás un equipo para crear tu idea única de cómo cambiar al mundo o bien, como lo llamamos en la red de Evoke - tu Evokacion. Dicha Evokacion será creada a medida que vayas respondiendo a las 8 misiones que te serán asignadas. Al final de este proceso, la red invertirá Evocoins en tu Evokacion. Las 10 Evokaciones que reciben las inversiones más altas serán revisadas y evaluadas por un Comité de Expertos, y los 3 mejores recibirán reconocimiento y premiación. 
Como equipo deberán cumplir con las 6 actividades propuestas por cada misión para avanzar a la siguiente misión. Al completar las actividades, tus poderes se incrementan.
<br><br>Hay 16 poderes únicos que puedes desarrollar, los que a su vez, te darán tus super-poderes - visionario creativo, colaborador con compromiso, pensador de sistemas y líder empático. Estos poderes te van a ayudar en el viaje dentro de la experiencia Evoke. 
<br><br>También vas a ganar Evocoins - la moneda que se usa en la red de Evoke - cada vez que contribuyas a mejorar la calidad de los pensamientos colectivos a través de darle poderes a otros o comentar sobre sus propias evidencias y/o contribuciones. Las monedas Evocoins serán usadas al final de esta experiencia para invertir en aquellas ideas innovadoras y cambiantes del mundo que creas que tendrán un mayor impacto en la comunidad, en tu país, o en el mundo. <br><br>Durante las 16 semanas, también se te dará la oportunidad de cambiar tus Evocoins para solicitar ayuda en completar tu Evokacion al usar la herramienta de Evoke - accediendo a transporte, materiales, y otra formas de asistencia que se proveerán… a un costo en Evocoins.
<br><br>Buena suerte Agentes! No veo la hora de ver sus progresos y reconocer su aporte a la Evokacion Final al terminar esta experiencia.',
    'You can also earn points towards 3 more Super Powers with the Powers below. Submit quality evidence to advance in your powers.' => '',
    'Add new Power' => 'Añadir nuevo Poder',
    'Additional Powers' => 'Poderes Adicionales',
    'Agent Type' => 'Tipo de agente',
    'Answer all the order questions from 1 to 4.' => 'Responde a todas las preguntas de la orden de 1 a 4',
    'Are you sure you want to delete this item?' => 'Está seguro que quiere eliminar este item?',
    'Are you sure you want to delete this power?' => 'Está seguro que quiere eliminar este poder?',
    'Are you sure you want to delete this quality?' => 'Está seguro que quiere eliminar esta cualidad?',
    'Are you sure you want to delete this superhero identity?' => 'stá seguro que quiere eliminar esta identidad de super héroe?',
    'Are you sure you want to delete this translation?' => 'Está seguro que quiere eliminar esta traducción?',
    'Auth Mode' => 'Modo de autenticación',
    'Based on your answers' => 'Con base en sus respuestas',
    'Based on your answers to the Agent Type survey we have determined the best role for you is that of <strong>{item}</strong>.' => 'Con base en sus respuestas en el cuestionario, hemos determinado que el mejor papel para usted es de <strong>{item}</strong>.',
    'Choose one answer for each single-choice question.' => 'Elija una respuesta para cada pregunta de selección simple',
    'Complete Profile' => 'Perfil Completo',
    'Contentcontainer ID' => 'Identificación de Contentcontainer',
    'Create' => 'Crear',
    'Create Matching Answer Translation' => 'Crear nueva Traducción de Respuesta Asociada',
    'Create Matching Answer Translations' => 'Crear traducciones de Respuesta Asociada',
    'Create Matching Answers' => 'Crear la Traducción de la respuesta asociada',
    'Create Matching Question Translation' => 'Crear la Traducción de la pregunta asociada',
    'Create Matching Question Translations' => 'Crear la Traducción de la pregunta asociada',
    'Create Qualities' => 'Crear Cualidades',
    'Create Quality Powers' => 'Crear Poderes de Cualidad',
    'Create Quality Translations' => 'Crear traducciones de cualidad',
    'Create Superhero Identities' => 'Crear identidades de superhéroes',
    'Create Superhero Identity Translations' => 'Crear Traducciones de Identidad de Superhéro',
    'Create new Matching Answer' => 'Crear nueva Respuesta Asociada',
    'Create new Matching Question' => 'Crear nueva Pregunta Asociada',
    'Create new Quality' => 'Crear nueva Cualidad',
    'Create new Superhero Identity' => 'Crear nueva Identidad de Superhéroe',
    'Create new Translation' => 'Crear nueva Traducción',
    'Created' => 'Creado',
    'Created At' => 'Creado en',
    'Created By' => 'Creado por',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Email' => 'Email',
    'Furthermore, you are already gifted with the <strong>{item}</strong>' => 'Además, ya está dotado de <strong>{item}</strong>',
    'Getting started' => 'Empezando',
    'Group ID' => 'Identificación de grupo',
    'Guid' => 'Guid',
    'ID' => 'Identificación',
    'ID Code' => 'Código ID',
    'Image' => 'Imagen',
    'In case of redirect, please make sure to answer all questions' => 'En caso de redirección, por favor asegúrese de responder a todas las preguntas',
    'Language' => 'Idioma',
    'Language ID' => 'Identificación de idioma',
    'Last Activity Email' => 'ùltimo email de actividad',
    'Last Login' => 'Último acesso',
    'Level {level}' => 'Nivel {level}',
    'Matching Answer' => 'Respuesta Asociada',
    'Matching Answer ID' => 'Identificación de respuesta asociada',
    'Matching Answer Translations' => 'Traducciones de respuesta asociada',
    'Matching Answers' => 'Respuestas Asociadas',
    'Matching Aswer ID' => 'Identificación de respuesta asociada',
    'Matching Question' => 'Pregunta Asociada',
    'Matching Question ID' => 'Identificación de pregunta asociada',
    'Matching Question Translations' => 'Traducciones de pregunta asociada',
    'Matching Questions' => 'Preguntas Asociadas',
    'Modified' => 'Modificado',
    'Name' => 'Nombre',
    'No images uploaded yet' => 'No hay imágenes subidas aún',
    'No matching question translations created yet!' => 'No existe traducción para las preguntas asociadas aún!',
    'No matching questions created yet!' => 'No existen preguntas asociadas aún!',
    'No missions created yet!' => 'No hay Misiones creadas aún!',
    'No qualities created yet!' => 'No hay Cualidades creadas aún!',
    'No quality powers created yet!' => 'No hay poderes de cualidad creados aún!',
    'No quality translations created yet!' => 'No hay traducciones para las cualidades creadas aún!',
    'No superhero identity created yet!' => 'No hay una identidad de Superhéroe creada aún!',
    'No superhero identity translations created yet!' => 'No hay traducciones de la identidad de Superhéroe creadas aún!',
    'Order' => 'Ordenar',
    'Order questions from 1 to 4. Do not repeat numbers.' => 'Ordene esas preguntas de 1 a 4. No repetir los números',
    'Powers:' => 'Poderes:',
    'Primary Power' => 'Poder Primario',
    'Primary Quality' => 'Cualidad Primaria',
    'Qualities' => 'Cualidades',
    'Quality' => 'Cualidad',
    'Quality 1' => 'Cualidad 1',
    'Quality 2' => 'Cualidad 2',
    'Quality ID' => 'Identificación de cualidad',
    'Quality Powers' => 'Poderes de Cualidad',
    'Quality Translations' => 'Traducciones de cualidad',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Secondary Power' => 'Poder Secundario',
    'Secondary Quality' => 'Cualidad Secundaria',
    'Select Option' => 'Seleccionar opción',
    'Select Power' => 'Seleccionar Poder',
    'Short Name' => 'Nombre Corto',
    'Single Choice' => 'Selección Simple',
    'Status' => 'Estado',
    'Submit' => 'Enviar',
    'Super Admin' => 'Superadministrador',
    'Super Power' => 'Súper Poder',
    'Super Power. {description}.' => 'Súper Poder. {description}.',
    'Superhero Identities' => 'Identidades de Superhéroe',
    'Superhero Identity' => 'Identidad de Superhéroe',
    'Superhero Identity ID' => 'Identificación de identidad de superhéroe',
    'Superhero Identity Translation' => 'Traducción de Identidad de Superhéroe',
    'Superhero Identity Translations' => 'Traducciones de identidad de superhéroe',
    'Tags' => 'Etiquetas',
    'The powers that you possess are:' => 'Los poderes que posees son:',
    'Time Zone' => 'Huso horario',
    'Title' => 'Título',
    'Translations' => 'Traducciones',
    'Type' => 'Tipo',
    'Update' => 'Actualizar',
    'Update Matching Answer' => 'Actualizar Respuesta Asociada',
    'Update Matching Answer Translation' => 'Actualizar Traducción de Respuesta Asociada',
    'Update Matching Question Translation' => 'Actualizar Traducción de Pregunta Asociada',
    'Update Matching Questions' => 'Actualizar Preguntas Asociadas',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated' => 'Actualizado',
    'Updated At' => 'Actualizado en',
    'Updated By' => 'Actualizado por',
    'Uploaded Image: {file}' => 'Imagen Subida: {file}',
    'User ID' => 'Identidad de usuario',
    'Username' => 'Nombre de usuario',
    'View Matching Answers' => 'Ver Respuestas Asociadas',
    'View Powers' => 'Ver Poderes',
    'View translations' => 'Ver traducciones',
    'Visibility' => 'Visibilidad',
    'Wall ID' => 'Identificación del muro',
    'With the powers you already possess, you are closest to achieving:' => 'Según los poderes que posees, estás más cerca de lograr:',
    'You can develop all of the superpowers by completing each of the mission activities.' => 'En esta plataforma podrás enviar evidencias para completar actividades dentro de las misiones. Así desarrollarás todos los superpoderes.',
    'Your Powers' => 'Sus Poderes',
    'Your Super Powers' => 'Sus Super Poderes',
    'Your powers are the reason why I have summoned you. They are the skills that qualify you to be part of the Evoke network. Now it is time to be your best. Over the course of this experience you must develop the four fundamental superpowers of Evoke agents:' => 'Tus poderes son la razón por la que te he convocado. Son las competencias que te cualifican para hacer parte de la red Evoke. Sin embargo, esta es una red en expansión, y en el transcurso de tu experiencia debes desarrollar los cuatro superpoderes fundamentales de los agentes Evoke:',
    'Your survey results' => 'Sus resultados',
    'Your survey results are:' => 'Sus resultados son:',
    'Your {power} Powers:' => 'Sus {power} Poderes:',
    'gifted power' => 'poder dado',
    'level' => 'nivel',
    'other powers' => 'otros poderes',
    'points' => 'puntos',
    '{point} points' => '{points} puntos',
];
