<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Registration Link' => 'Invitación para unirte a la Red Evoke',
    'Sign up' => 'Regístrate aquí',
    'Welcome to %appName%' => 'Bienvenido a %appName%',
    'Welcome to %appName%. Please click on the button below to proceed with your registration.' => 'Bienvenido a %appName%.Por favor, haz clic en el botón de abajo para proceder a registrarte.',
    'This is Alchemy, and this is an Urgent Evoke. Wherever you are, whoever you are, if you found this message, it\'s your destiny to join us.' => 'Aqui es Alchemy, y esto es un Evokación Urgente. Donde quiera que estés, quienquiera que seas, si encontrases este mensaje, es tu destino unirte a nosotros.',
    'Evoke is a network of social innovators that use their powers to save the world. And this is an invitation to join us.<br><br>During the next 16 weeks you and your team will complete 8 missions and create with the community an Evokation -- your team project that seeks to solve problems in your community of Soacha.  At the end of this journey, the Evoke network will recognize the best Evokations.<br><br>Evoke is counting on you' => 'Evoke es una red de innovadores sociales que usan sus poderes para salvar al mundo. Y esto es una invitación a unirse a nosotros. Durante las próximas 16 semanas, usted y su equipo completarán 8 misiones y crearán con la comunidad un proyecto Evokation - su equipo que busca resolver problemas en su comunidad de Soacha . Al final de este viaje, la red Evoke reconocerá las mejores evokaciones. <br> <br> Evoke cuenta con usted',
    'Sign Up' => 'Regístrate aquí',
];
