<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Account' => 'Crear Cuenta',
    '<strong>Agent</strong> registration' => 'Registro de <strong>Agente</strong>',
    '“This is Alchemy, and this is an Urgent Evoke. Wherever you are, whoever you are, if you found this message, it\'s your destiny to join us.”' => '“Soy Alchemy, y este es un Evoke urgente. No importa dónde estás o quién eres, si encontraste este mensaje, tu destino es unirte a nosotros.”',
    'You have demonstrated your courage, and your commitment is unquestionable. The first thing we need is to update the Evoke database Evoke with the following fields:' => 'Acabas de probar tu valentía. Tu compromiso como agente es incuestionable. Lo primero que necesitamos es ingresarte la base de datos de Evoke llenando los siguientes campos:', 
];
