<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Account</strong> registration' => '',
    'Create Account' => 'Crear Cuenta',
    'This is Alchemy, and this is an Urgent Evoke. Wherever you are, whoever you are, if you found this message, it\'s your destiny to join us.' => 'Aqui es Alchemy, y esto es un Evokación Urgente. Donde quiera que estés, quienquiera que seas, si encontrases este mensaje, es tu destino unirte a nosotros.',
    'You have demonstrated your courage, and your commitment is unquestionable. The first thing we need is to update the Evoke database Evoke with the following fields:' => 'Usted ha demostrado su coraje, y su compromiso es incuestionable. Lo primero que necesitamos es actualizar la base Evoke con los siguientes campos:',
];
