<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<br>A social network to increase your communication and teamwork.<br>Register now
                                                        to join this space.' => '<br>Un nuevo concepto de red social.<br>Registrate ahora para unirte a este espacio.',
    '<br>A social network to increase your communication and teamwork.<br>Register now
to join this space.' => '<br>Un nuevo concepto de red social.<br>Registrate ahora para unirte a este espacio.',
    'Sign up now' => 'Inscríbete ahora',
    'Space Invite' => 'Invitaciones de espacio',
    'You got a <strong>space</strong> invite' => 'Tienes una invitación a un <strong>espacio</strong>',
    'invited you to the space:' => 'te invitó al espacio: ',
    '<br>I am Alchemy, and this is an urgent Evoke. No matter where you are or who you are, if you found this message, your destiny is to join us. <br><br>Evoke is the network of social innovators who use their powers to save the world. And this is an invitation for you to make part of it.<br><br>For the next 16 weeks, you and your team will complete 8 missions and create with the community an "Evokation", a personal project that seeks to solve some of the problems in Soacha. By the end, the Evoke network will award the best Evokations. <br><br>Evoke counts on you.' => '<br>Soy Alchemy, y este es un Evoke urgente. No importa dónde estás o quién eres, si encontraste este mensaje, tu destino es unirte a nosotros. <br><br>Evoke es la red de innovadores sociales que usan sus poderes para salvar el mundo. Y esta es una invitación para que hagas parte de ella. <br><br>Durante las siguientes 16 semanas tú y tu equipo completarán 8 misiones y crearán con la comunidad una “evokación”, un proyecto personal que busca solucionar algunas de las problemáticas en Soacha. Al final, la Red Evoke reconocerá las mejores evokaciones. <br><br>Evoke cuenta contigo.',
    'Register Here' => 'Regístrate aquí',
];
