<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '10 Evocoin(s)!' => '10 Evocoin(s)!',
    '20 Evocoin(s)!' => '20 Evocoin(s)!',
    '5 Evocoin(s)!' => '5 Evocoin(s)!',
    '50 Evocoin(s)!' => '50 Evocoin(s)!',
    'Better luck next time!' => '¡Mejor suerte la próxima vez!',
    'Create' => 'Crear',
    'Create Prize' => 'Crear Premio',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Discover Tools' => 'Descubre Herramientas',
    'Download here instructions to the boardgame.' => 'Descarga aquí las instrucciones para el juego de mesa.',
    'Download instructions PDF' => 'Instrucciones de descarga PDF',
    'Edit' => 'Editar',
    'Edit ' => 'Editar ',
    'Evocoin(s)' => 'Evocoin(s)',
    'Evoke Tools' => 'Herramientas de Evoke',
    'ID' => 'Identificación',
    'Image' => 'Imagen',
    'Located in Soacha, this game was designed by a secret team from the network to ensure countless hours of fun with your team of agents. When you play, you can win evocoins both to use the slot machine and to invest in your Evokations portfolio' => 'Localizado en Soacha, este juego fue diseñado por un equipo secreto de la red para garantizar incontables horas de diversión con tu equipo de agentes. Al jugar, podrás ganar evocoins para usar tanto en la máquina tragamonedas como para invertir en tu portafolio de Evokaciones.',
    'Name' => 'Nombre',
    'Not Enough Evocoin!' => 'No hay suficiente Evocoin!',
    'Pay 5 Evocoins to play' => 'Paga 5 Evocoins para jugar',
    'Powers' => 'Poderes',
    'Prizes' => 'Premios',
    'Quantity' => 'Cantidad',
    'Slot Machine' => 'Máquina Tragamonedas',
    'Sorry!' => '¡Perdón!',
    'The Boardgame' => 'Juego de Mesa',
    'Tools remaining: {total}' => 'Herramientas restantes: {total}',
    'Try your luck' => 'Prueba tu suerte',
    'Try your luck to win support in our slot machine. Every attempt will cost 5 evocoins.' => 'Prueba tu suerte para ganar ayudas en nuestra máquina tragamonedas. Cada intento te costará 5 evocoins.',
    'Update' => 'Actualizar',
    'We introduce some tools the network has made available to facilitate your agent work in Soacha.' => 'Te presentamos algunas herramientas que la red ha puesto a tu disposición para facilitar tu labor de agente en Soacha.',
    'Week of' => 'Semana de',
    'Weight' => 'Peso',
];
