<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

 return [
   'Create' => '',
   'Name'   => '',
   'ID'     => '',
   'Created At' => '',
   'Modified At' => '',
   'Prizes' => '',
   'Weight' => '',
   'Quantity' => '',
   'Week of' => '',
   'Delete' => '',
   'Edit' => '',
   'Create Prizes' => '',
   'This should be the begining of the week for this prize' => '',
   'Evoke Tools' => '',
   'Not Enough Evocoin!' => '',
   'Costs 5 Evocoin' => '',
   'Sorry' => 'Sorry, nothing was found.',
   'Discover Tools' => '',
   'Tools Description' => 'Officia deserunt ut reprehenderit aliqua commodo consectetur culpa. Ullamco in laborum veniam ullamco do qui proident eiusmod proident nulla consectetur.',
   'Pay 5 Evocoins to play' => '',
   'Tools remaining:' => '',
   'Boardgame intro' => 'Proident eiusmod ex dolore dolore ut ad tempor. Mollit officia tempor sunt aute ut occaecat officia adipisicing. Do in labore amet consectetur aliquip ut voluptate esse nostrud mollit eiusmod irure. Anim ad proident veniam sit deserunt nostrud ad veniam ut incididunt adipisicing mollit in cupidatat. Labore sint quis nulla culpa quis duis elit nulla dolore commodo ullamco pariatur laboris enim reprehenderit magna veniam.',
   'Instructions intro' => 'Consectetur irure proident proident enim eiusmod voluptate aute nisi ad eu pariatur et proident incididunt reprehenderit aute ad.Lorem veniam minim esse eu sit qui pariatur voluptate occaecat minim in ipsum.',
   'Dowload instructions PDF' => '',
   'Roles' => '',
   'Earn super powers' => 'Earn Super Powers to unlock roles in the game. Level up for more powerful roles.',
   'Better luck next time!' => '',
 ];
