<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
 return [
     'Create' => 'Crear',
     'Create Product' => 'Crear Producto',
     'Delete' => 'Borrar',
     'Description' => 'Descripción',
     'Edit' => 'Editar',
     'Evocoin(s)' => '',
     'ID' => '',
     'Image' => 'Imagen',
     'Name' => 'Nombre',
     'Price' => 'Precio',
     'Product' => 'Producto',
     'Products' => 'Productos',
     'Quantity' => 'Cantidad',
     'Update' => 'Actualizar',
     'User' => 'Usario',
     'Sold Out' => 'Agotado',
     'Buy' => 'Comprar',
     'Offer your time!' => 'Ofrecer su tiempo!',
     'Sorry you do not have enough evocoin!' => 'No hay suficiente Evocoin!',
     'You successfully bought {product}' => 'Compraste {prodcut}',
     'Sorry, something went wrong with your purchase' => '',
     'As a mentor you can offer your time to the agents to help with their projects, activities, or offer guidance.' => 'Como un mentor, puede ofrecer su tiempo a los agentes para ayudarles con sus proyectos, actividades, o ofrecer consejos.',
     'Time' => 'Tiempo',
     'in minutes' => 'en minutos',
     'Please describe the nature of the mentoring offered:' => 'Por favor describir el tipo de ayuda ofrecida:',
     'Click to mark as fulfilled' => 'Hacer clic para señalar cumplido',
     'Fulfilled' => 'Cumplido',
     'Fulfill' => 'Cumplir',
     'Bought Time' => 'Tiempo Comprado',
     'Bought Products' => 'Productos Comprados',
     'Unfulfilled Products' => 'Productos no Cumplidos',
     'Fulfilled Products' => 'Productos Cumplidos',
     'return' => 'devolver',
     "You successfully returned {product}!" => 'Devolviste {prodcuts}!',
     'Sorry, something went wrong with your return' => '',
     'You successfully fulfilled time for {username}!' => 'Cumpliste tiempo por {username}!',
     'Offered Products' => 'Productos Ofrecidos',
     'You can view your bought products' => 'Puede ver sus productos comprados',
     'on your profile' => 'en su perfil',
 ];
