<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'As a mentor you can offer your time to the agents to help with their projects, activities, or offer guidance.' => 'Como mentor, puedes ofrecer su tiempo a los agentes para ayudar con sus proyectos, actividades u ofrecer orientación.',
    'Bought Products' => 'Comprar productos',
    'Buy' => 'Comprar',
    'Click to mark as fulfilled' => 'Clica para marcar como cumplido',
    'Fulfill' => 'Cumplir',
    'Fulfilled?' => 'Cumplido?',
    'Marketplace' => 'Mercado',
    'Mentoring' => 'Mentoría',
    'No' => 'No',
    'No images uploaded yet' => 'No hay imágenes aún',
    'Offer your time' => 'Ofrezca su tiempo',
    'Offer your time!' => 'Ofrezca su tiempo!',
    'Please describe the nature of the mentoring offered:' => 'Describa la naturaleza de la mentóría ofrecida',
    'Price' => 'Precio',
    'Product' => 'Producto',
    'Product ID' => 'Identificación de Producto',
    'Products' => 'Productos',
    'Sold Out' => 'Agotado',
    'Sorry you do not have enough evocoin!' => 'Lo siento, no tienes suficiente evocoin!',
    'Sorry, something went wrong with your purchase' => 'Lo siento, algo ha salió mal con sua compra',
    'Time' => 'Tiempo',
    'Unfulfill' => 'No ha cumplido',
    'Uploaded Image: {file}' => 'Imagen subida: {file}',
    'User ID' => 'Identificación de Usuário',
    'Yes' => 'Sí',
    'You successfully bought {product}!' => 'Ha comprado {product} con éxito!',
    'in minutes' => 'en minutos',
    'Create' => 'Crear',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Edit' => 'Editar',
    'Evocoin(s)' => 'Evocoin(s)',
    'ID' => 'Identificación',
    'Image' => 'Imagen',
    'Name' => 'Nombre',
    'Quantity' => 'Cantidad',
    'Update' => 'Actualizar',
    'User' => 'Usuario',
    'Offered Products' => 'Productos Ofrecidos',
    'You can view your bought products' => 'Puede ver sus productos comprados',
    'on your profile' => 'en su perfil',
    'Bought Time' => 'Tiempo Comprado',
    'Bought Products' => 'Productos Comprados',
    'Unfulfilled Products' => 'Productos Pendientes',
    'Fulfilled Products' => 'Productos Cumplidos',
    'return' => 'devolver',
    "You successfully returned {product}!" => 'Devolviste {prodcuts}!',
    'Sorry, something went wrong with your return' => '',
    'You successfully fulfilled time for {username}!' => 'Cumpliste tiempo por {username}!',
];
